create table dgf_ffp_dlr_dstrbn_dtls (
	dstrbnId LONG not null primary key,
	dlrRegNo LONG,
	ffpRegstrId LONG,
	selLingDate DATE null,
	commodityId LONG,
	commodityName VARCHAR(30) null,
	sellingPrice VARCHAR(4) null,
	sellingQty LONG,
	stockBfrSelling LONG,
	stockAfterSelling LONG,
	createDate DATE null,
	createdBy LONG,
	companyId LONG,
	inventoryId LONG
);

create table dgf_ffp_invtory_dtls (
	inventoryId LONG not null primary key,
	dlrRegNo LONG,
	allcNtfyNo LONG,
	fromDate DATE null,
	toDate DATE null,
	commodityId LONG,
	commodityName VARCHAR(30) null,
	noOfIndents LONG,
	receivedQty DOUBLE,
	soldQty DOUBLE,
	balanceQty DOUBLE,
	createDate LONG,
	companyId LONG,
	createdBy LONG
);

create table dgf_ffp_oms_allc_ntfy_dtls (
	allocNtfyId VARCHAR(30) not null primary key,
	prgrmType VARCHAR(30) null,
	salesOrgName VARCHAR(30) null,
	dstrbtnChnnl VARCHAR(30) null,
	year LONG,
	salesOffice VARCHAR(30) null,
	memoNo VARCHAR(30) null,
	startDate DATE null,
	endDate DATE null,
	duration VARCHAR(75) null,
	commodityId LONG,
	commodityName VARCHAR(30) null,
	econmcPrice LONG,
	salePrceToEndCstmr LONG,
	unitPrice VARCHAR(30) null,
	maxAlltmntPDay DOUBLE,
	maxSellQtyPCstmr DOUBLE,
	createDate DATE null
);

create table dgf_ffpb_details (
	ffpRegstrId LONG not null primary key,
	nationalId LONG,
	dlrRegNo LONG,
	ffpCardNo VARCHAR(30) null,
	dateOfBirth DATE null,
	mobileNo VARCHAR(12) null,
	emialId VARCHAR(30) null,
	maritalStatus LONG,
	gender LONG,
	spouseNid LONG,
	prstAddrRegion VARCHAR(5) null,
	prstAddrDisrict VARCHAR(5) null,
	prstAddrUpzilla VARCHAR(5) null,
	prstAddrUnion VARCHAR(5) null,
	prstAddrVillage VARCHAR(30) null,
	prstAddrWard VARCHAR(30) null,
	prstAddrZip LONG,
	prstAddrPstoffc LONG,
	prstAddrHoseaddr VARCHAR(75) null,
	ffpApplCrtdBy LONG,
	createDate DATE null,
	ffpApplMdfyBy LONG,
	modifiedDate DATE null,
	groupId LONG,
	companyId LONG,
	applApprejCmnts VARCHAR(50) null,
	ffpbApplStatus LONG,
	version DOUBLE,
	status LONG,
	statusByUserId LONG,
	statusDate DATE null
);