/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.service.base;

import bd.gov.dgfood.food.friendly.program.model.DlrFfpOmsAllcNtfyDetails;
import bd.gov.dgfood.food.friendly.program.service.DlrFfpOmsAllcNtfyDetailsService;
import bd.gov.dgfood.food.friendly.program.service.DlrFfpOmsAllcNtfyDetailsServiceUtil;
import bd.gov.dgfood.food.friendly.program.service.persistence.DlrDistributionDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.DlrFfpOmsAllcNtfyDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.FfpbDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.InvtoryDetailsPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the dlr ffp oms allc ntfy details remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.food.friendly.program.service.impl.DlrFfpOmsAllcNtfyDetailsServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.food.friendly.program.service.impl.DlrFfpOmsAllcNtfyDetailsServiceImpl
 * @generated
 */
public abstract class DlrFfpOmsAllcNtfyDetailsServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, DlrFfpOmsAllcNtfyDetailsService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DlrFfpOmsAllcNtfyDetailsService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DlrFfpOmsAllcNtfyDetailsServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DlrFfpOmsAllcNtfyDetailsService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dlrFfpOmsAllcNtfyDetailsService =
			(DlrFfpOmsAllcNtfyDetailsService)aopProxy;

		_setServiceUtilService(dlrFfpOmsAllcNtfyDetailsService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DlrFfpOmsAllcNtfyDetailsService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DlrFfpOmsAllcNtfyDetails.class;
	}

	protected String getModelClassName() {
		return DlrFfpOmsAllcNtfyDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dlrFfpOmsAllcNtfyDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		DlrFfpOmsAllcNtfyDetailsService dlrFfpOmsAllcNtfyDetailsService) {

		try {
			Field field =
				DlrFfpOmsAllcNtfyDetailsServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dlrFfpOmsAllcNtfyDetailsService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DlrDistributionDetailsPersistence
		dlrDistributionDetailsPersistence;

	@Reference
	protected bd.gov.dgfood.food.friendly.program.service.
		DlrFfpOmsAllcNtfyDetailsLocalService
			dlrFfpOmsAllcNtfyDetailsLocalService;

	protected DlrFfpOmsAllcNtfyDetailsService dlrFfpOmsAllcNtfyDetailsService;

	@Reference
	protected DlrFfpOmsAllcNtfyDetailsPersistence
		dlrFfpOmsAllcNtfyDetailsPersistence;

	@Reference
	protected FfpbDetailsPersistence ffpbDetailsPersistence;

	@Reference
	protected InvtoryDetailsPersistence invtoryDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		DlrFfpOmsAllcNtfyDetailsServiceBaseImpl.class);

}