/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.service.base;

import bd.gov.dgfood.food.friendly.program.model.InvtoryDetails;
import bd.gov.dgfood.food.friendly.program.service.InvtoryDetailsLocalService;
import bd.gov.dgfood.food.friendly.program.service.InvtoryDetailsLocalServiceUtil;
import bd.gov.dgfood.food.friendly.program.service.persistence.DlrDistributionDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.DlrFfpOmsAllcNtfyDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.FfpbDetailsPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.InvtoryDetailsPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the invtory details local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.food.friendly.program.service.impl.InvtoryDetailsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.food.friendly.program.service.impl.InvtoryDetailsLocalServiceImpl
 * @generated
 */
public abstract class InvtoryDetailsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, InvtoryDetailsLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InvtoryDetailsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>InvtoryDetailsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the invtory details to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InvtoryDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param invtoryDetails the invtory details
	 * @return the invtory details that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InvtoryDetails addInvtoryDetails(InvtoryDetails invtoryDetails) {
		invtoryDetails.setNew(true);

		return invtoryDetailsPersistence.update(invtoryDetails);
	}

	/**
	 * Creates a new invtory details with the primary key. Does not add the invtory details to the database.
	 *
	 * @param inventoryId the primary key for the new invtory details
	 * @return the new invtory details
	 */
	@Override
	@Transactional(enabled = false)
	public InvtoryDetails createInvtoryDetails(long inventoryId) {
		return invtoryDetailsPersistence.create(inventoryId);
	}

	/**
	 * Deletes the invtory details with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InvtoryDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param inventoryId the primary key of the invtory details
	 * @return the invtory details that was removed
	 * @throws PortalException if a invtory details with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InvtoryDetails deleteInvtoryDetails(long inventoryId)
		throws PortalException {

		return invtoryDetailsPersistence.remove(inventoryId);
	}

	/**
	 * Deletes the invtory details from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InvtoryDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param invtoryDetails the invtory details
	 * @return the invtory details that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InvtoryDetails deleteInvtoryDetails(InvtoryDetails invtoryDetails) {
		return invtoryDetailsPersistence.remove(invtoryDetails);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return invtoryDetailsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			InvtoryDetails.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return invtoryDetailsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.food.friendly.program.model.impl.InvtoryDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return invtoryDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.food.friendly.program.model.impl.InvtoryDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return invtoryDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return invtoryDetailsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return invtoryDetailsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public InvtoryDetails fetchInvtoryDetails(long inventoryId) {
		return invtoryDetailsPersistence.fetchByPrimaryKey(inventoryId);
	}

	/**
	 * Returns the invtory details with the primary key.
	 *
	 * @param inventoryId the primary key of the invtory details
	 * @return the invtory details
	 * @throws PortalException if a invtory details with the primary key could not be found
	 */
	@Override
	public InvtoryDetails getInvtoryDetails(long inventoryId)
		throws PortalException {

		return invtoryDetailsPersistence.findByPrimaryKey(inventoryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(invtoryDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InvtoryDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("inventoryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			invtoryDetailsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(InvtoryDetails.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"inventoryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(invtoryDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InvtoryDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("inventoryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return invtoryDetailsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement InvtoryDetailsLocalServiceImpl#deleteInvtoryDetails(InvtoryDetails) to avoid orphaned data");
		}

		return invtoryDetailsLocalService.deleteInvtoryDetails(
			(InvtoryDetails)persistedModel);
	}

	@Override
	public BasePersistence<InvtoryDetails> getBasePersistence() {
		return invtoryDetailsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return invtoryDetailsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the invtory detailses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.food.friendly.program.model.impl.InvtoryDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of invtory detailses
	 * @param end the upper bound of the range of invtory detailses (not inclusive)
	 * @return the range of invtory detailses
	 */
	@Override
	public List<InvtoryDetails> getInvtoryDetailses(int start, int end) {
		return invtoryDetailsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of invtory detailses.
	 *
	 * @return the number of invtory detailses
	 */
	@Override
	public int getInvtoryDetailsesCount() {
		return invtoryDetailsPersistence.countAll();
	}

	/**
	 * Updates the invtory details in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InvtoryDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param invtoryDetails the invtory details
	 * @return the invtory details that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InvtoryDetails updateInvtoryDetails(InvtoryDetails invtoryDetails) {
		return invtoryDetailsPersistence.update(invtoryDetails);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InvtoryDetailsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		invtoryDetailsLocalService = (InvtoryDetailsLocalService)aopProxy;

		_setLocalServiceUtilService(invtoryDetailsLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InvtoryDetailsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return InvtoryDetails.class;
	}

	protected String getModelClassName() {
		return InvtoryDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = invtoryDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		InvtoryDetailsLocalService invtoryDetailsLocalService) {

		try {
			Field field = InvtoryDetailsLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, invtoryDetailsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DlrDistributionDetailsPersistence
		dlrDistributionDetailsPersistence;

	@Reference
	protected DlrFfpOmsAllcNtfyDetailsPersistence
		dlrFfpOmsAllcNtfyDetailsPersistence;

	@Reference
	protected FfpbDetailsPersistence ffpbDetailsPersistence;

	protected InvtoryDetailsLocalService invtoryDetailsLocalService;

	@Reference
	protected InvtoryDetailsPersistence invtoryDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		InvtoryDetailsLocalServiceBaseImpl.class);

}