/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DlrDistributionDetails service. Represents a row in the &quot;dgf_ffp_dlr_dstrbn_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.friendly.program.model.impl.DlrDistributionDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.friendly.program.model.impl.DlrDistributionDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DlrDistributionDetails
 * @generated
 */
@ProviderType
public interface DlrDistributionDetailsModel
	extends BaseModel<DlrDistributionDetails>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dlr distribution details model instance should use the {@link DlrDistributionDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this dlr distribution details.
	 *
	 * @return the primary key of this dlr distribution details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dlr distribution details.
	 *
	 * @param primaryKey the primary key of this dlr distribution details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dstrbn ID of this dlr distribution details.
	 *
	 * @return the dstrbn ID of this dlr distribution details
	 */
	public long getDstrbnId();

	/**
	 * Sets the dstrbn ID of this dlr distribution details.
	 *
	 * @param dstrbnId the dstrbn ID of this dlr distribution details
	 */
	public void setDstrbnId(long dstrbnId);

	/**
	 * Returns the dlr reg no of this dlr distribution details.
	 *
	 * @return the dlr reg no of this dlr distribution details
	 */
	public long getDlrRegNo();

	/**
	 * Sets the dlr reg no of this dlr distribution details.
	 *
	 * @param dlrRegNo the dlr reg no of this dlr distribution details
	 */
	public void setDlrRegNo(long dlrRegNo);

	/**
	 * Returns the ffp regstr ID of this dlr distribution details.
	 *
	 * @return the ffp regstr ID of this dlr distribution details
	 */
	public long getFfpRegstrId();

	/**
	 * Sets the ffp regstr ID of this dlr distribution details.
	 *
	 * @param ffpRegstrId the ffp regstr ID of this dlr distribution details
	 */
	public void setFfpRegstrId(long ffpRegstrId);

	/**
	 * Returns the sel ling date of this dlr distribution details.
	 *
	 * @return the sel ling date of this dlr distribution details
	 */
	public Date getSelLingDate();

	/**
	 * Sets the sel ling date of this dlr distribution details.
	 *
	 * @param selLingDate the sel ling date of this dlr distribution details
	 */
	public void setSelLingDate(Date selLingDate);

	/**
	 * Returns the commodity ID of this dlr distribution details.
	 *
	 * @return the commodity ID of this dlr distribution details
	 */
	public long getCommodityId();

	/**
	 * Sets the commodity ID of this dlr distribution details.
	 *
	 * @param commodityId the commodity ID of this dlr distribution details
	 */
	public void setCommodityId(long commodityId);

	/**
	 * Returns the commodity name of this dlr distribution details.
	 *
	 * @return the commodity name of this dlr distribution details
	 */
	@AutoEscape
	public String getCommodityName();

	/**
	 * Sets the commodity name of this dlr distribution details.
	 *
	 * @param commodityName the commodity name of this dlr distribution details
	 */
	public void setCommodityName(String commodityName);

	/**
	 * Returns the selling price of this dlr distribution details.
	 *
	 * @return the selling price of this dlr distribution details
	 */
	@AutoEscape
	public String getSellingPrice();

	/**
	 * Sets the selling price of this dlr distribution details.
	 *
	 * @param sellingPrice the selling price of this dlr distribution details
	 */
	public void setSellingPrice(String sellingPrice);

	/**
	 * Returns the selling qty of this dlr distribution details.
	 *
	 * @return the selling qty of this dlr distribution details
	 */
	public long getSellingQty();

	/**
	 * Sets the selling qty of this dlr distribution details.
	 *
	 * @param sellingQty the selling qty of this dlr distribution details
	 */
	public void setSellingQty(long sellingQty);

	/**
	 * Returns the stock bfr selling of this dlr distribution details.
	 *
	 * @return the stock bfr selling of this dlr distribution details
	 */
	public long getStockBfrSelling();

	/**
	 * Sets the stock bfr selling of this dlr distribution details.
	 *
	 * @param stockBfrSelling the stock bfr selling of this dlr distribution details
	 */
	public void setStockBfrSelling(long stockBfrSelling);

	/**
	 * Returns the stock after selling of this dlr distribution details.
	 *
	 * @return the stock after selling of this dlr distribution details
	 */
	public long getStockAfterSelling();

	/**
	 * Sets the stock after selling of this dlr distribution details.
	 *
	 * @param stockAfterSelling the stock after selling of this dlr distribution details
	 */
	public void setStockAfterSelling(long stockAfterSelling);

	/**
	 * Returns the create date of this dlr distribution details.
	 *
	 * @return the create date of this dlr distribution details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dlr distribution details.
	 *
	 * @param createDate the create date of this dlr distribution details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this dlr distribution details.
	 *
	 * @return the created by of this dlr distribution details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this dlr distribution details.
	 *
	 * @param createdBy the created by of this dlr distribution details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the company ID of this dlr distribution details.
	 *
	 * @return the company ID of this dlr distribution details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dlr distribution details.
	 *
	 * @param companyId the company ID of this dlr distribution details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the inventory ID of this dlr distribution details.
	 *
	 * @return the inventory ID of this dlr distribution details
	 */
	public long getInventoryId();

	/**
	 * Sets the inventory ID of this dlr distribution details.
	 *
	 * @param inventoryId the inventory ID of this dlr distribution details
	 */
	public void setInventoryId(long inventoryId);

	@Override
	public DlrDistributionDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}