/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DlrFfpOmsAllcNtfyDetails service. Represents a row in the &quot;dgf_ffp_oms_allc_ntfy_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.friendly.program.model.impl.DlrFfpOmsAllcNtfyDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.friendly.program.model.impl.DlrFfpOmsAllcNtfyDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DlrFfpOmsAllcNtfyDetails
 * @generated
 */
@ProviderType
public interface DlrFfpOmsAllcNtfyDetailsModel
	extends BaseModel<DlrFfpOmsAllcNtfyDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dlr ffp oms allc ntfy details model instance should use the {@link DlrFfpOmsAllcNtfyDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this dlr ffp oms allc ntfy details.
	 *
	 * @return the primary key of this dlr ffp oms allc ntfy details
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this dlr ffp oms allc ntfy details.
	 *
	 * @param primaryKey the primary key of this dlr ffp oms allc ntfy details
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the alloc ntfy ID of this dlr ffp oms allc ntfy details.
	 *
	 * @return the alloc ntfy ID of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getAllocNtfyId();

	/**
	 * Sets the alloc ntfy ID of this dlr ffp oms allc ntfy details.
	 *
	 * @param allocNtfyId the alloc ntfy ID of this dlr ffp oms allc ntfy details
	 */
	public void setAllocNtfyId(String allocNtfyId);

	/**
	 * Returns the prgrm type of this dlr ffp oms allc ntfy details.
	 *
	 * @return the prgrm type of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getPrgrmType();

	/**
	 * Sets the prgrm type of this dlr ffp oms allc ntfy details.
	 *
	 * @param prgrmType the prgrm type of this dlr ffp oms allc ntfy details
	 */
	public void setPrgrmType(String prgrmType);

	/**
	 * Returns the sales org name of this dlr ffp oms allc ntfy details.
	 *
	 * @return the sales org name of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getSalesOrgName();

	/**
	 * Sets the sales org name of this dlr ffp oms allc ntfy details.
	 *
	 * @param salesOrgName the sales org name of this dlr ffp oms allc ntfy details
	 */
	public void setSalesOrgName(String salesOrgName);

	/**
	 * Returns the dstrbtn chnnl of this dlr ffp oms allc ntfy details.
	 *
	 * @return the dstrbtn chnnl of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getDstrbtnChnnl();

	/**
	 * Sets the dstrbtn chnnl of this dlr ffp oms allc ntfy details.
	 *
	 * @param dstrbtnChnnl the dstrbtn chnnl of this dlr ffp oms allc ntfy details
	 */
	public void setDstrbtnChnnl(String dstrbtnChnnl);

	/**
	 * Returns the year of this dlr ffp oms allc ntfy details.
	 *
	 * @return the year of this dlr ffp oms allc ntfy details
	 */
	public long getYear();

	/**
	 * Sets the year of this dlr ffp oms allc ntfy details.
	 *
	 * @param year the year of this dlr ffp oms allc ntfy details
	 */
	public void setYear(long year);

	/**
	 * Returns the sales office of this dlr ffp oms allc ntfy details.
	 *
	 * @return the sales office of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getSalesOffice();

	/**
	 * Sets the sales office of this dlr ffp oms allc ntfy details.
	 *
	 * @param salesOffice the sales office of this dlr ffp oms allc ntfy details
	 */
	public void setSalesOffice(String salesOffice);

	/**
	 * Returns the memo no of this dlr ffp oms allc ntfy details.
	 *
	 * @return the memo no of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getMemoNo();

	/**
	 * Sets the memo no of this dlr ffp oms allc ntfy details.
	 *
	 * @param memoNo the memo no of this dlr ffp oms allc ntfy details
	 */
	public void setMemoNo(String memoNo);

	/**
	 * Returns the start date of this dlr ffp oms allc ntfy details.
	 *
	 * @return the start date of this dlr ffp oms allc ntfy details
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this dlr ffp oms allc ntfy details.
	 *
	 * @param startDate the start date of this dlr ffp oms allc ntfy details
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this dlr ffp oms allc ntfy details.
	 *
	 * @return the end date of this dlr ffp oms allc ntfy details
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this dlr ffp oms allc ntfy details.
	 *
	 * @param endDate the end date of this dlr ffp oms allc ntfy details
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the duration of this dlr ffp oms allc ntfy details.
	 *
	 * @return the duration of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getDuration();

	/**
	 * Sets the duration of this dlr ffp oms allc ntfy details.
	 *
	 * @param duration the duration of this dlr ffp oms allc ntfy details
	 */
	public void setDuration(String duration);

	/**
	 * Returns the commodity ID of this dlr ffp oms allc ntfy details.
	 *
	 * @return the commodity ID of this dlr ffp oms allc ntfy details
	 */
	public long getCommodityId();

	/**
	 * Sets the commodity ID of this dlr ffp oms allc ntfy details.
	 *
	 * @param commodityId the commodity ID of this dlr ffp oms allc ntfy details
	 */
	public void setCommodityId(long commodityId);

	/**
	 * Returns the commodity name of this dlr ffp oms allc ntfy details.
	 *
	 * @return the commodity name of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getCommodityName();

	/**
	 * Sets the commodity name of this dlr ffp oms allc ntfy details.
	 *
	 * @param commodityName the commodity name of this dlr ffp oms allc ntfy details
	 */
	public void setCommodityName(String commodityName);

	/**
	 * Returns the econmc price of this dlr ffp oms allc ntfy details.
	 *
	 * @return the econmc price of this dlr ffp oms allc ntfy details
	 */
	public long getEconmcPrice();

	/**
	 * Sets the econmc price of this dlr ffp oms allc ntfy details.
	 *
	 * @param econmcPrice the econmc price of this dlr ffp oms allc ntfy details
	 */
	public void setEconmcPrice(long econmcPrice);

	/**
	 * Returns the sale prce to end cstmr of this dlr ffp oms allc ntfy details.
	 *
	 * @return the sale prce to end cstmr of this dlr ffp oms allc ntfy details
	 */
	public long getSalePrceToEndCstmr();

	/**
	 * Sets the sale prce to end cstmr of this dlr ffp oms allc ntfy details.
	 *
	 * @param salePrceToEndCstmr the sale prce to end cstmr of this dlr ffp oms allc ntfy details
	 */
	public void setSalePrceToEndCstmr(long salePrceToEndCstmr);

	/**
	 * Returns the unit price of this dlr ffp oms allc ntfy details.
	 *
	 * @return the unit price of this dlr ffp oms allc ntfy details
	 */
	@AutoEscape
	public String getUnitPrice();

	/**
	 * Sets the unit price of this dlr ffp oms allc ntfy details.
	 *
	 * @param unitPrice the unit price of this dlr ffp oms allc ntfy details
	 */
	public void setUnitPrice(String unitPrice);

	/**
	 * Returns the max alltmnt p day of this dlr ffp oms allc ntfy details.
	 *
	 * @return the max alltmnt p day of this dlr ffp oms allc ntfy details
	 */
	public float getMaxAlltmntPDay();

	/**
	 * Sets the max alltmnt p day of this dlr ffp oms allc ntfy details.
	 *
	 * @param maxAlltmntPDay the max alltmnt p day of this dlr ffp oms allc ntfy details
	 */
	public void setMaxAlltmntPDay(float maxAlltmntPDay);

	/**
	 * Returns the max sell qty p cstmr of this dlr ffp oms allc ntfy details.
	 *
	 * @return the max sell qty p cstmr of this dlr ffp oms allc ntfy details
	 */
	public float getMaxSellQtyPCstmr();

	/**
	 * Sets the max sell qty p cstmr of this dlr ffp oms allc ntfy details.
	 *
	 * @param maxSellQtyPCstmr the max sell qty p cstmr of this dlr ffp oms allc ntfy details
	 */
	public void setMaxSellQtyPCstmr(float maxSellQtyPCstmr);

	/**
	 * Returns the create date of this dlr ffp oms allc ntfy details.
	 *
	 * @return the create date of this dlr ffp oms allc ntfy details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dlr ffp oms allc ntfy details.
	 *
	 * @param createDate the create date of this dlr ffp oms allc ntfy details
	 */
	public void setCreateDate(Date createDate);

	@Override
	public DlrFfpOmsAllcNtfyDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}