/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FfpbDetails service. Represents a row in the &quot;dgf_ffpb_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.friendly.program.model.impl.FfpbDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.friendly.program.model.impl.FfpbDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FfpbDetails
 * @generated
 */
@ProviderType
public interface FfpbDetailsModel extends BaseModel<FfpbDetails>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ffpb details model instance should use the {@link FfpbDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this ffpb details.
	 *
	 * @return the primary key of this ffpb details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ffpb details.
	 *
	 * @param primaryKey the primary key of this ffpb details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ffp regstr ID of this ffpb details.
	 *
	 * @return the ffp regstr ID of this ffpb details
	 */
	public long getFfpRegstrId();

	/**
	 * Sets the ffp regstr ID of this ffpb details.
	 *
	 * @param ffpRegstrId the ffp regstr ID of this ffpb details
	 */
	public void setFfpRegstrId(long ffpRegstrId);

	/**
	 * Returns the national ID of this ffpb details.
	 *
	 * @return the national ID of this ffpb details
	 */
	public long getNationalId();

	/**
	 * Sets the national ID of this ffpb details.
	 *
	 * @param nationalId the national ID of this ffpb details
	 */
	public void setNationalId(long nationalId);

	/**
	 * Returns the dlr reg no of this ffpb details.
	 *
	 * @return the dlr reg no of this ffpb details
	 */
	public long getDlrRegNo();

	/**
	 * Sets the dlr reg no of this ffpb details.
	 *
	 * @param dlrRegNo the dlr reg no of this ffpb details
	 */
	public void setDlrRegNo(long dlrRegNo);

	/**
	 * Returns the ffp card no of this ffpb details.
	 *
	 * @return the ffp card no of this ffpb details
	 */
	@AutoEscape
	public String getFfpCardNo();

	/**
	 * Sets the ffp card no of this ffpb details.
	 *
	 * @param ffpCardNo the ffp card no of this ffpb details
	 */
	public void setFfpCardNo(String ffpCardNo);

	/**
	 * Returns the date of birth of this ffpb details.
	 *
	 * @return the date of birth of this ffpb details
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this ffpb details.
	 *
	 * @param dateOfBirth the date of birth of this ffpb details
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the mobile no of this ffpb details.
	 *
	 * @return the mobile no of this ffpb details
	 */
	@AutoEscape
	public String getMobileNo();

	/**
	 * Sets the mobile no of this ffpb details.
	 *
	 * @param mobileNo the mobile no of this ffpb details
	 */
	public void setMobileNo(String mobileNo);

	/**
	 * Returns the emial ID of this ffpb details.
	 *
	 * @return the emial ID of this ffpb details
	 */
	@AutoEscape
	public String getEmialId();

	/**
	 * Sets the emial ID of this ffpb details.
	 *
	 * @param emialId the emial ID of this ffpb details
	 */
	public void setEmialId(String emialId);

	/**
	 * Returns the marital status of this ffpb details.
	 *
	 * @return the marital status of this ffpb details
	 */
	public long getMaritalStatus();

	/**
	 * Sets the marital status of this ffpb details.
	 *
	 * @param maritalStatus the marital status of this ffpb details
	 */
	public void setMaritalStatus(long maritalStatus);

	/**
	 * Returns the gender of this ffpb details.
	 *
	 * @return the gender of this ffpb details
	 */
	public long getGender();

	/**
	 * Sets the gender of this ffpb details.
	 *
	 * @param gender the gender of this ffpb details
	 */
	public void setGender(long gender);

	/**
	 * Returns the spouse nid of this ffpb details.
	 *
	 * @return the spouse nid of this ffpb details
	 */
	public long getSpouseNid();

	/**
	 * Sets the spouse nid of this ffpb details.
	 *
	 * @param spouseNid the spouse nid of this ffpb details
	 */
	public void setSpouseNid(long spouseNid);

	/**
	 * Returns the prst addr region of this ffpb details.
	 *
	 * @return the prst addr region of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrRegion();

	/**
	 * Sets the prst addr region of this ffpb details.
	 *
	 * @param prstAddrRegion the prst addr region of this ffpb details
	 */
	public void setPrstAddrRegion(String prstAddrRegion);

	/**
	 * Returns the prst addr disrict of this ffpb details.
	 *
	 * @return the prst addr disrict of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrDisrict();

	/**
	 * Sets the prst addr disrict of this ffpb details.
	 *
	 * @param prstAddrDisrict the prst addr disrict of this ffpb details
	 */
	public void setPrstAddrDisrict(String prstAddrDisrict);

	/**
	 * Returns the prst addr upzilla of this ffpb details.
	 *
	 * @return the prst addr upzilla of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrUpzilla();

	/**
	 * Sets the prst addr upzilla of this ffpb details.
	 *
	 * @param prstAddrUpzilla the prst addr upzilla of this ffpb details
	 */
	public void setPrstAddrUpzilla(String prstAddrUpzilla);

	/**
	 * Returns the prst addr union of this ffpb details.
	 *
	 * @return the prst addr union of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrUnion();

	/**
	 * Sets the prst addr union of this ffpb details.
	 *
	 * @param prstAddrUnion the prst addr union of this ffpb details
	 */
	public void setPrstAddrUnion(String prstAddrUnion);

	/**
	 * Returns the prst addr village of this ffpb details.
	 *
	 * @return the prst addr village of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrVillage();

	/**
	 * Sets the prst addr village of this ffpb details.
	 *
	 * @param prstAddrVillage the prst addr village of this ffpb details
	 */
	public void setPrstAddrVillage(String prstAddrVillage);

	/**
	 * Returns the prst addr ward of this ffpb details.
	 *
	 * @return the prst addr ward of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrWard();

	/**
	 * Sets the prst addr ward of this ffpb details.
	 *
	 * @param prstAddrWard the prst addr ward of this ffpb details
	 */
	public void setPrstAddrWard(String prstAddrWard);

	/**
	 * Returns the prst addr zip of this ffpb details.
	 *
	 * @return the prst addr zip of this ffpb details
	 */
	public long getPrstAddrZip();

	/**
	 * Sets the prst addr zip of this ffpb details.
	 *
	 * @param prstAddrZip the prst addr zip of this ffpb details
	 */
	public void setPrstAddrZip(long prstAddrZip);

	/**
	 * Returns the prst addr pstoffc of this ffpb details.
	 *
	 * @return the prst addr pstoffc of this ffpb details
	 */
	public long getPrstAddrPstoffc();

	/**
	 * Sets the prst addr pstoffc of this ffpb details.
	 *
	 * @param prstAddrPstoffc the prst addr pstoffc of this ffpb details
	 */
	public void setPrstAddrPstoffc(long prstAddrPstoffc);

	/**
	 * Returns the prst addr hoseaddr of this ffpb details.
	 *
	 * @return the prst addr hoseaddr of this ffpb details
	 */
	@AutoEscape
	public String getPrstAddrHoseaddr();

	/**
	 * Sets the prst addr hoseaddr of this ffpb details.
	 *
	 * @param prstAddrHoseaddr the prst addr hoseaddr of this ffpb details
	 */
	public void setPrstAddrHoseaddr(String prstAddrHoseaddr);

	/**
	 * Returns the ffp appl crtd by of this ffpb details.
	 *
	 * @return the ffp appl crtd by of this ffpb details
	 */
	public long getFfpApplCrtdBy();

	/**
	 * Sets the ffp appl crtd by of this ffpb details.
	 *
	 * @param ffpApplCrtdBy the ffp appl crtd by of this ffpb details
	 */
	public void setFfpApplCrtdBy(long ffpApplCrtdBy);

	/**
	 * Returns the create date of this ffpb details.
	 *
	 * @return the create date of this ffpb details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ffpb details.
	 *
	 * @param createDate the create date of this ffpb details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the ffp appl mdfy by of this ffpb details.
	 *
	 * @return the ffp appl mdfy by of this ffpb details
	 */
	public long getFfpApplMdfyBy();

	/**
	 * Sets the ffp appl mdfy by of this ffpb details.
	 *
	 * @param ffpApplMdfyBy the ffp appl mdfy by of this ffpb details
	 */
	public void setFfpApplMdfyBy(long ffpApplMdfyBy);

	/**
	 * Returns the modified date of this ffpb details.
	 *
	 * @return the modified date of this ffpb details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ffpb details.
	 *
	 * @param modifiedDate the modified date of this ffpb details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this ffpb details.
	 *
	 * @return the group ID of this ffpb details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ffpb details.
	 *
	 * @param groupId the group ID of this ffpb details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ffpb details.
	 *
	 * @return the company ID of this ffpb details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ffpb details.
	 *
	 * @param companyId the company ID of this ffpb details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the appl apprej cmnts of this ffpb details.
	 *
	 * @return the appl apprej cmnts of this ffpb details
	 */
	@AutoEscape
	public String getApplApprejCmnts();

	/**
	 * Sets the appl apprej cmnts of this ffpb details.
	 *
	 * @param applApprejCmnts the appl apprej cmnts of this ffpb details
	 */
	public void setApplApprejCmnts(String applApprejCmnts);

	/**
	 * Returns the ffpb appl status of this ffpb details.
	 *
	 * @return the ffpb appl status of this ffpb details
	 */
	public long getFfpbApplStatus();

	/**
	 * Sets the ffpb appl status of this ffpb details.
	 *
	 * @param ffpbApplStatus the ffpb appl status of this ffpb details
	 */
	public void setFfpbApplStatus(long ffpbApplStatus);

	/**
	 * Returns the version of this ffpb details.
	 *
	 * @return the version of this ffpb details
	 */
	public float getVersion();

	/**
	 * Sets the version of this ffpb details.
	 *
	 * @param version the version of this ffpb details
	 */
	public void setVersion(float version);

	/**
	 * Returns the status of this ffpb details.
	 *
	 * @return the status of this ffpb details
	 */
	public long getStatus();

	/**
	 * Sets the status of this ffpb details.
	 *
	 * @param status the status of this ffpb details
	 */
	public void setStatus(long status);

	/**
	 * Returns the status by user ID of this ffpb details.
	 *
	 * @return the status by user ID of this ffpb details
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this ffpb details.
	 *
	 * @param statusByUserId the status by user ID of this ffpb details
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this ffpb details.
	 *
	 * @return the status by user uuid of this ffpb details
	 */
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this ffpb details.
	 *
	 * @param statusByUserUuid the status by user uuid of this ffpb details
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this ffpb details.
	 *
	 * @return the status date of this ffpb details
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this ffpb details.
	 *
	 * @param statusDate the status date of this ffpb details
	 */
	public void setStatusDate(Date statusDate);

	@Override
	public FfpbDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}