/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InvtoryDetails service. Represents a row in the &quot;dgf_ffp_invtory_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.friendly.program.model.impl.InvtoryDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.friendly.program.model.impl.InvtoryDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvtoryDetails
 * @generated
 */
@ProviderType
public interface InvtoryDetailsModel
	extends BaseModel<InvtoryDetails>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invtory details model instance should use the {@link InvtoryDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this invtory details.
	 *
	 * @return the primary key of this invtory details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invtory details.
	 *
	 * @param primaryKey the primary key of this invtory details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inventory ID of this invtory details.
	 *
	 * @return the inventory ID of this invtory details
	 */
	public long getInventoryId();

	/**
	 * Sets the inventory ID of this invtory details.
	 *
	 * @param inventoryId the inventory ID of this invtory details
	 */
	public void setInventoryId(long inventoryId);

	/**
	 * Returns the dlr reg no of this invtory details.
	 *
	 * @return the dlr reg no of this invtory details
	 */
	public long getDlrRegNo();

	/**
	 * Sets the dlr reg no of this invtory details.
	 *
	 * @param dlrRegNo the dlr reg no of this invtory details
	 */
	public void setDlrRegNo(long dlrRegNo);

	/**
	 * Returns the allc ntfy no of this invtory details.
	 *
	 * @return the allc ntfy no of this invtory details
	 */
	public long getAllcNtfyNo();

	/**
	 * Sets the allc ntfy no of this invtory details.
	 *
	 * @param allcNtfyNo the allc ntfy no of this invtory details
	 */
	public void setAllcNtfyNo(long allcNtfyNo);

	/**
	 * Returns the from date of this invtory details.
	 *
	 * @return the from date of this invtory details
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this invtory details.
	 *
	 * @param fromDate the from date of this invtory details
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this invtory details.
	 *
	 * @return the to date of this invtory details
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this invtory details.
	 *
	 * @param toDate the to date of this invtory details
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the commodity ID of this invtory details.
	 *
	 * @return the commodity ID of this invtory details
	 */
	public long getCommodityId();

	/**
	 * Sets the commodity ID of this invtory details.
	 *
	 * @param commodityId the commodity ID of this invtory details
	 */
	public void setCommodityId(long commodityId);

	/**
	 * Returns the commodity name of this invtory details.
	 *
	 * @return the commodity name of this invtory details
	 */
	@AutoEscape
	public String getCommodityName();

	/**
	 * Sets the commodity name of this invtory details.
	 *
	 * @param commodityName the commodity name of this invtory details
	 */
	public void setCommodityName(String commodityName);

	/**
	 * Returns the no of indents of this invtory details.
	 *
	 * @return the no of indents of this invtory details
	 */
	public long getNoOfIndents();

	/**
	 * Sets the no of indents of this invtory details.
	 *
	 * @param noOfIndents the no of indents of this invtory details
	 */
	public void setNoOfIndents(long noOfIndents);

	/**
	 * Returns the received qty of this invtory details.
	 *
	 * @return the received qty of this invtory details
	 */
	public float getReceivedQty();

	/**
	 * Sets the received qty of this invtory details.
	 *
	 * @param receivedQty the received qty of this invtory details
	 */
	public void setReceivedQty(float receivedQty);

	/**
	 * Returns the sold qty of this invtory details.
	 *
	 * @return the sold qty of this invtory details
	 */
	public float getSoldQty();

	/**
	 * Sets the sold qty of this invtory details.
	 *
	 * @param soldQty the sold qty of this invtory details
	 */
	public void setSoldQty(float soldQty);

	/**
	 * Returns the balance qty of this invtory details.
	 *
	 * @return the balance qty of this invtory details
	 */
	public float getBalanceQty();

	/**
	 * Sets the balance qty of this invtory details.
	 *
	 * @param balanceQty the balance qty of this invtory details
	 */
	public void setBalanceQty(float balanceQty);

	/**
	 * Returns the create date of this invtory details.
	 *
	 * @return the create date of this invtory details
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this invtory details.
	 *
	 * @param createDate the create date of this invtory details
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the company ID of this invtory details.
	 *
	 * @return the company ID of this invtory details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this invtory details.
	 *
	 * @param companyId the company ID of this invtory details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this invtory details.
	 *
	 * @return the created by of this invtory details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this invtory details.
	 *
	 * @param createdBy the created by of this invtory details
	 */
	public void setCreatedBy(long createdBy);

	@Override
	public InvtoryDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}