create table dgf_dlr_perf_dtls (
	dgf_dlr_perf_id LONG not null primary key,
	national_id VARCHAR(75) null,
	dlr_reg_appl_no LONG,
	dlr_reg_no LONG,
	dlr_perf_yr1 LONG,
	dlr_perf_yr1_alloc_qty LONG,
	dlr_perf_yr1_comdty_qty LONG,
	dlr_perf_yr1_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr1_rmrk VARCHAR(75) null,
	dlr_perf_yr2 LONG,
	dlr_perf_yr2_alloc_qty LONG,
	dlr_perf_yr2_comdty_qty LONG,
	dlr_perf_yr2_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr2_rmrk VARCHAR(75) null,
	dlr_perf_yr3 LONG,
	dlr_perf_yr3_alloc_qty LONG,
	dlr_perf_yr3_comdty_qty LONG,
	dlr_perf_yr3_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr3_rmrk VARCHAR(75) null,
	version LONG
);

create table dgf_dlr_reg_addl_dtls (
	dlr_reg_addl_dtls_id LONG not null primary key,
	national_id VARCHAR(75) null,
	dlr_reg_appl_no LONG,
	dlr_reg_no LONG,
	pblc_rep INTEGER,
	wrk_in_govt INTEGER,
	physcly_chlngd INTEGER,
	phscly_chln_gd_attch_id LONG,
	license_type VARCHAR(75) null,
	third_party_ops_flg LONG,
	fmly_dlr_shp_no LONG,
	dlrshp_fmly_mmbr_name VARCHAR(75) null,
	dlrshp_fmly_mmbr_type VARCHAR(75) null,
	dlr_shp_trck_typ_flg INTEGER,
	trck_licns_plat_no VARCHAR(75) null,
	trck_cpcty LONG,
	trck_make VARCHAR(75) null,
	trck_model VARCHAR(75) null,
	trck_rent_own_flg VARCHAR(75) null,
	trck_mfg_yr LONG,
	shp_length LONG,
	shp_height LONG,
	shp_width LONG,
	shp_strg_cpcty LONG,
	shp_flr_cmntd INTEGER,
	shp_sign_brd INTEGER,
	dlr_licns_posses INTEGER,
	dlr_run_shp_himself INTEGER,
	dlr_fmly_dlr_shp_flg LONG,
	version LONG
);

create table dgf_dlr_reg_dtls (
	dlr_reg_no LONG not null primary key,
	national_id VARCHAR(75) null,
	user_id LONG,
	group_id LONG,
	company_id LONG,
	dlr_reg_appl_no LONG,
	fgl_licns_no VARCHAR(75) null,
	fgl_licns_issue_date DATE null,
	trd_licns_no LONG,
	trd_licns_exp_date DATE null,
	dlr_type_id VARCHAR(75) null,
	marital_status VARCHAR(75) null,
	spouse_name VARCHAR(75) null,
	spouse_fthr_name VARCHAR(75) null,
	spouse_nid VARCHAR(75) null,
	spouse_brth_date DATE null,
	dlr_reg_expiry_date DATE null,
	sap_bu_code VARCHAR(75) null,
	dlr_reg_appl_status VARCHAR(75) null,
	dlr_reg_crtd_date DATE null,
	pymnt_trn_ref_no LONG,
	pymnt_trn_status VARCHAR(75) null,
	challan_doc_id LONG,
	incm_tax_attch_id LONG,
	bnk_solvncy_cert_id LONG,
	shp_ownship_docu_id LONG,
	shp_rented_docu_id LONG,
	signature_id LONG,
	dlr_appr_rjct_comments VARCHAR(75) null,
	dlr_reg_appr_rej_rmrk VARCHAR(75) null,
	status INTEGER,
	status_by_user_id LONG,
	status_by_user_name VARCHAR(75) null,
	status_date DATE null,
	version LONG,
	dlr_reg_crtd_by VARCHAR(75) null,
	create_date DATE null,
	last_updtd_by LONG,
	modifed_date DATE null,
	dlr_oms_sub_type VARCHAR(75) null,
	division LONG,
	district LONG,
	upzilla LONG,
	union_name LONG,
	dlr_brth_date DATE null
);

create table dgf_dlr_updt_temp_dtls (
	dgf_dlr_update_req_id LONG not null primary key,
	national_id VARCHAR(75) null,
	dlr_reg_no LONG,
	marital_status VARCHAR(75) null,
	spouse_name VARCHAR(75) null,
	spouse_fthr_name VARCHAR(75) null,
	spouse_nid VARCHAR(75) null,
	spouse_brth_date DATE null,
	pblc_rep INTEGER,
	wrk_in_govt INTEGER,
	physcly_chlngd INTEGER,
	phscly_chlngd_attch_id LONG,
	shp_division LONG,
	shp_district LONG,
	shp_upzilla LONG,
	shp_union LONG,
	shp_village VARCHAR(75) null,
	shp_ward VARCHAR(75) null,
	shp_zip_code VARCHAR(75) null,
	shp_pst_offc VARCHAR(75) null,
	shp_present_address VARCHAR(75) null,
	shp_location VARCHAR(75) null,
	shp_length LONG,
	shp_height LONG,
	shp_width LONG,
	shp_strg_cpcty LONG,
	shp_flr_cmntd INTEGER,
	shp_sign_brd INTEGER,
	license_type VARCHAR(75) null,
	thrd_party_ops_flg LONG,
	dlrshp_fmly_mmbr_name VARCHAR(75) null,
	dlrshp_fmly_mmbr_type VARCHAR(75) null,
	dlr_perf_yr1 LONG,
	dlr_perf_yr1_alloc_qty LONG,
	dlr_perf_yr1_comdty_qty LONG,
	dlr_perf_yr1_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr1_rmrk VARCHAR(75) null,
	dlr_perf_yr2 LONG,
	dlr_perf_yr2_alloc_qty LONG,
	dlr_perf_yr2_comdty_qty LONG,
	dlr_perf_yr2_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr2_rmrk VARCHAR(75) null,
	dlr_perf_yr3 LONG,
	dlr_perf_yr3_alloc_qty LONG,
	dlr_perf_yr3_comdty_qty LONG,
	dlr_perf_yr3_dlr_ctgry VARCHAR(75) null,
	dlr_perf_yr3_rmrk VARCHAR(75) null,
	trck_licns_plat_no VARCHAR(75) null,
	trck_cpcty LONG,
	trck_make VARCHAR(75) null,
	trck_model VARCHAR(75) null,
	trck_rent_own_flg VARCHAR(75) null,
	trck_mfg_yr LONG,
	version LONG,
	status INTEGER,
	status_by_user_id LONG,
	status_by_user_name VARCHAR(75) null,
	status_date DATE null,
	create_date DATE null,
	last_updtd_by LONG,
	modified_date DATE null,
	foodgrain_license INTEGER,
	trade_license INTEGER,
	tcv_dlr_license INTEGER,
	import_license INTEGER,
	license_essential_goods INTEGER,
	trade_license_agriculture INTEGER,
	dlr_oms_sub_type VARCHAR(75) null,
	user_id LONG,
	group_id LONG,
	company_id LONG,
	dlr_run_shp_himself INTEGER,
	dlr_shp_trck_typ_flg INTEGER
);

create table dgf_dlr_withdrawal (
	dlr_withdrawal_id LONG not null primary key,
	national_id VARCHAR(75) null,
	license_no VARCHAR(75) null,
	dealer_name VARCHAR(75) null,
	mobile_no VARCHAR(75) null,
	reason VARCHAR(75) null,
	program_type VARCHAR(75) null,
	oms_sub_type VARCHAR(75) null,
	created_date DATE null,
	modified_by LONG,
	modified_date DATE null,
	user_id LONG,
	group_id LONG,
	company_id LONG,
	dlr_reg_no LONG,
	reg_appl_no LONG,
	status INTEGER,
	status_by_user_id LONG,
	status_by_user_name VARCHAR(75) null,
	status_date DATE null
);