create table dgf_attachments (
	attchmId LONG not null primary key,
	nationalId LONG,
	attachmentCatagory VARCHAR(75) null,
	attachmntDate DATE null,
	fileEntryId LONG,
	title VARCHAR(1000) null,
	filePath VARCHAR(1000) null,
	version LONG,
	openTextId LONG,
	status LONG,
	lastUpdatedDate DATE null,
	lastUpdatedBy LONG
);

create table dgf_beneficiary_other_info (
	id LONG not null primary key,
	verified_id LONG,
	marital_status VARCHAR(1) null,
	spouse_name VARCHAR(500) null,
	spouse_nid VARCHAR(40) null,
	spouse_second_nid VARCHAR(40) null,
	spouse_dob DATE null,
	father_nid VARCHAR(40) null,
	mother_nid VARCHAR(40) null,
	mobile_no VARCHAR(11) null,
	mobile_no_relation VARCHAR(1) null,
	ec_spouse_info TEXT null,
	occupation VARCHAR(200) null,
	village_name VARCHAR(240) null,
	word_no VARCHAR(100) null,
	dealer_name VARCHAR(200) null,
	dealer_mobile VARCHAR(100) null,
	mobile_verified_at DATE null,
	family_earning_member LONG,
	avg_family_income LONG,
	dependent_family_member LONG,
	land_size LONG,
	land_unit VARCHAR(120) null,
	remarks VARCHAR(900) null,
	user_id LONG,
	created_at DATE null,
	updated_at DATE null,
	dealer_slug VARCHAR(200) null,
	dealer_id LONG
);

create table dgf_bnk_chlln_dtls (
	bnkChllnId LONG not null primary key,
	trnPoNo LONG,
	paymentStatus LONG,
	trnAmount LONG,
	pymntChllnDate DATE null,
	bnkChllnDocId LONG,
	bnkChllnUpldBy LONG
);

create table dgf_buss_addr_dtls (
	businessAddressId LONG not null primary key,
	nationalId LONG,
	businessDivision LONG,
	businessDistrict LONG,
	businessUpzilla LONG,
	businessUnionName LONG,
	businessVillage VARCHAR(75) null,
	businessWard VARCHAR(75) null,
	businessZipCode VARCHAR(75) null,
	businessPostOffice VARCHAR(75) null,
	businessHouseAddress VARCHAR(75) null
);

create table dgf_dealer_masters (
	id LONG not null primary key,
	union_id LONG,
	dealer_name VARCHAR(250) null,
	dealer_name_en VARCHAR(250) null,
	dealer_slug VARCHAR(250) null,
	father_name VARCHAR(250) null,
	mother_name VARCHAR(250) null,
	birth_date DATE null,
	gender VARCHAR(10) null,
	image_path_real VARCHAR(500) null,
	image_path_ec VARCHAR(500) null,
	ec_pm_division VARCHAR(50) null,
	ec_pm_district VARCHAR(50) null,
	ec_pm_rmo VARCHAR(50) null,
	ec_pm_upazila VARCHAR(250) null,
	ec_pm_union_ward VARCHAR(250) null,
	ec_pm_ward_union_porishod VARCHAR(250) null,
	ec_pm_post_office VARCHAR(250) null,
	ec_pm_postal_code VARCHAR(50) null,
	ec_pm_mouza_moholla VARCHAR(250) null,
	ec_pm_additional_mouza_moholla VARCHAR(250) null,
	ec_pm_village_road VARCHAR(250) null,
	ec_pm_additional_village_road VARCHAR(250) null,
	ec_pm_home_holding_no VARCHAR(250) null,
	ec_pm_region VARCHAR(100) null,
	ec_pr_division VARCHAR(150) null,
	ec_pr_district VARCHAR(150) null,
	ec_pr_rmo VARCHAR(150) null,
	ec_pr_upazila VARCHAR(250) null,
	ec_pr_city_corp_municipality VARCHAR(250) null,
	ec_pr_union_ward VARCHAR(250) null,
	ec_pr_post_office VARCHAR(250) null,
	ec_pr_postal_code VARCHAR(50) null,
	ec_pr_ward_union_porishod VARCHAR(250) null,
	ec_pr_mouza_moholla VARCHAR(250) null,
	ec_pr_additional_mouza_moholla VARCHAR(250) null,
	ec_pr_village_road VARCHAR(250) null,
	ec_pr_additional_village_road VARCHAR(250) null,
	ec_pr_home_holding_no VARCHAR(250) null,
	ec_pr_region VARCHAR(100) null,
	ec_occupation VARCHAR(100) null,
	ec_blood_group VARCHAR(500) null,
	age LONG,
	pm_division_id LONG,
	pm_district_id LONG,
	pm_upazila_id LONG,
	pm_union_id LONG,
	pm_post_office VARCHAR(10) null,
	pm_word_no VARCHAR(10) null,
	pm_village VARCHAR(150) null,
	pm_holding_info VARCHAR(250) null,
	pr_division_id LONG,
	pr_district_id LONG,
	pr_upazila_id LONG,
	pr_union_id LONG,
	pr_post_office VARCHAR(10) null,
	pr_word_no VARCHAR(10) null,
	pr_village VARCHAR(150) null,
	pr_holding_info VARCHAR(250) null,
	dealer_mobile_no VARCHAR(11) null,
	dealer_national_id VARCHAR(75) null,
	second_national_id VARCHAR(75) null,
	spouse_name VARCHAR(250) null,
	spouse_father_name VARCHAR(250) null,
	spouse_birth_date DATE null,
	spouse_nid VARCHAR(10) null,
	spouse_second_nid VARCHAR(17) null,
	govt_employee VARCHAR(1) null,
	handicap VARCHAR(1) null,
	public_representative VARCHAR(1) null,
	vgd_status VARCHAR(1) null,
	card_no_from_one LONG,
	card_no_to_one LONG,
	card_no_from_two LONG,
	card_no_to_two LONG,
	card_no_from_three LONG,
	card_no_to_three LONG,
	status VARCHAR(1) null,
	created_at DATE null,
	updated_at DATE null,
	card_no_from_four LONG,
	card_no_to_four LONG,
	card_no_from_five LONG,
	card_no_to_five LONG,
	single_cards VARCHAR(1000) null,
	user_id LONG,
	additional_union_id LONG,
	upazila_id LONG,
	remarks VARCHAR(254) null
);

create table dgf_distribution_schedules (
	id VARCHAR(75) not null primary key,
	distribution_year LONG,
	distribution_month VARCHAR(75) null,
	open_status VARCHAR(75) null,
	start_date DATE null,
	end_date DATE null,
	remarks VARCHAR(75) null,
	user_id LONG,
	created_at DATE null,
	updated_at DATE null
);

create table dgf_dlr_distribution_dtls (
	id LONG not null primary key,
	dealer_id LONG,
	beneficiaries_id LONG,
	beneficiaries_mobile_no VARCHAR(75) null,
	card_no LONG,
	union_id LONG,
	distribution_date DATE null,
	distribution_qty LONG,
	status INTEGER,
	created_at DATE null,
	updated_at DATE null,
	month INTEGER,
	year INTEGER
);

create table dgf_duplct_licns_reason (
	duplicateLicenseReasonID LONG not null primary key,
	userId LONG,
	nationalId VARCHAR(75) null,
	licenseNo VARCHAR(75) null,
	licenseExpiryDate DATE null,
	tradeLicenseNo VARCHAR(75) null,
	tradeLicenseExpiryDate DATE null,
	tradeLicAttchId LONG,
	paymentAttchId LONG,
	applicationNo VARCHAR(75) null,
	licenseApplicationType VARCHAR(75) null,
	duplicateLicenseReasonDisplay VARCHAR(75) null,
	comments STRING null,
	createdDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null,
	fglPrePrimaryId LONG,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table dgf_fgl_lic_dtls (
	fglLicPrimaryId LONG not null primary key,
	nationalId VARCHAR(75) null,
	fglPrePrimaryId LONG,
	fglApplicationNo VARCHAR(75) null,
	foodgrainLicenseNo VARCHAR(75) null,
	foodgrainLicenseType VARCHAR(75) null,
	tradeLicenseNo VARCHAR(75) null,
	tradeLicenseExpiryDate DATE null,
	foodgrainLicenseIssueDate DATE null,
	foodgrainLicenseExpiryDate DATE null,
	foodgrainLicenseIssuedBy LONG,
	fglLicenseVersion LONG,
	productType VARCHAR(75) null
);

create table dgf_fgl_license_no (
	id LONG not null primary key,
	suffix LONG,
	prefix LONG,
	serial_no LONG,
	license_no VARCHAR(75) null,
	created_at DATE null,
	updated_at DATE null
);

create table dgf_fgl_pre_dtls (
	fglPrePrimaryId LONG not null primary key,
	nationalId LONG,
	fglApplicationNo VARCHAR(75) null,
	applicantName VARCHAR(75) null,
	tradeLicenseNo VARCHAR(75) null,
	tradeLicenseExpiryDate DATE null,
	tradeLicenseIssuerCode VARCHAR(75) null,
	tradeLicenseIssuerCity VARCHAR(75) null,
	businessIdentificationNo VARCHAR(75) null,
	taxIdentificationNo VARCHAR(75) null,
	businessName VARCHAR(75) null,
	businessType VARCHAR(75) null,
	paymentChallanId LONG,
	paymentStatus LONG,
	reviewComments VARCHAR(75) null,
	applicationStatus LONG,
	applicationStatusDate DATE null,
	duplicateLicenseReasonId LONG,
	comments VARCHAR(75) null,
	fglLicenseVersion LONG,
	foodGrainLicenseType VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	createdDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null,
	applicationStatusById LONG,
	presentAddrId LONG,
	bussinessAddrId LONG,
	tradeLicenseDocId LONG,
	bussIdentfctDocId LONG,
	taxIdentfctDocId LONG,
	bnkStatmtDocId LONG,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	userId LONG,
	birthDate DATE null,
	fglApplicationType VARCHAR(75) null,
	photographDocId LONG,
	otherReleventDocId LONG,
	electricExemptionMemoId LONG,
	envClrMemoId LONG,
	bstiClrMemoId LONG,
	fireLicNumDocId LONG,
	productType VARCHAR(75) null
);

create table dgf_fgl_product_dtls (
	fglProductPrimaryId LONG not null primary key,
	nationalId VARCHAR(75) null,
	fglLicPrimaryId LONG,
	productType VARCHAR(75) null,
	stockDuration LONG,
	stockAmount LONG,
	createdDate DATE null,
	createdBy LONG,
	modifiedDate DATE null,
	modifiedBy LONG
);

create table dgf_licns_user_regs (
	licUserId LONG not null primary key,
	nationalId VARCHAR(75) null,
	applicantName VARCHAR(75) null,
	tradeLicenseNo VARCHAR(75) null,
	tradeLicenseExpiryDate DATE null,
	tradeLicenseIssuerCode VARCHAR(75) null,
	tradeLicenseIssuerCity VARCHAR(75) null,
	businessIdentificationNo VARCHAR(75) null,
	taxIdentificationNo VARCHAR(75) null,
	businessName VARCHAR(75) null,
	businessType VARCHAR(75) null,
	businessDivision LONG,
	businessDistrict LONG,
	businessUpzilla LONG,
	businessUnionName LONG,
	businessVillage VARCHAR(75) null,
	businessWard VARCHAR(75) null,
	businessZipCode VARCHAR(75) null,
	businessPostOffice VARCHAR(75) null,
	businessHouseAddress VARCHAR(75) null,
	photographFile VARCHAR(1000) null,
	tradeLicDoc VARCHAR(1000) null,
	binDoc VARCHAR(1000) null,
	tinDoc VARCHAR(1000) null,
	bankStat VARCHAR(1000) null,
	otherReleventDoc VARCHAR(1000) null,
	comments VARCHAR(75) null,
	foodGrainLicenseType VARCHAR(75) null,
	division LONG,
	district LONG,
	upzilla LONG,
	unionName LONG,
	village VARCHAR(75) null,
	ward VARCHAR(75) null,
	zipCode VARCHAR(75) null,
	postOffice VARCHAR(75) null,
	houseAddress VARCHAR(75) null,
	password_ VARCHAR(75) null,
	fatherName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	motherName VARCHAR(75) null,
	gender VARCHAR(75) null,
	maritalStatus VARCHAR(75) null,
	birthDate DATE null,
	mobileNo VARCHAR(75) null,
	userId LONG,
	email VARCHAR(75) null,
	nidDivision VARCHAR(75) null,
	nidDistrict VARCHAR(75) null,
	nidUpzilla VARCHAR(75) null,
	nidUnion VARCHAR(75) null,
	nidVillage VARCHAR(75) null,
	nidWard VARCHAR(75) null,
	nidZipCode VARCHAR(75) null,
	nidPostOffice VARCHAR(75) null,
	nidHouseAddress VARCHAR(75) null,
	isSubmit BOOLEAN,
	electricExemptionMemo VARCHAR(1000) null,
	envClrMemo VARCHAR(1000) null,
	bstiClrMemo VARCHAR(1000) null,
	fireLicNumDoc VARCHAR(1000) null,
	productType VARCHAR(75) null
);

create table dgf_loc_district (
	id_ LONG not null primary key,
	divisionId LONG,
	name VARCHAR(75) null,
	bnName VARCHAR(75) null,
	lat VARCHAR(75) null,
	lon VARCHAR(75) null,
	url VARCHAR(75) null,
	status VARCHAR(75) null,
	createdAt DATE null,
	updatedAt DATE null,
	geoCode LONG
);

create table dgf_loc_division (
	id_ LONG not null primary key,
	name VARCHAR(75) null,
	bnName VARCHAR(75) null,
	url VARCHAR(75) null,
	status VARCHAR(75) null,
	createdAt DATE null,
	updatedAt DATE null,
	geoCode LONG
);

create table dgf_loc_subdistrict (
	id_ LONG not null primary key,
	districtId LONG,
	name VARCHAR(75) null,
	bnName VARCHAR(75) null,
	url VARCHAR(75) null,
	status VARCHAR(75) null,
	createdAt DATE null,
	updatedAt DATE null,
	geoCode LONG,
	roleName VARCHAR(75) null
);

create table dgf_loc_union (
	id_ LONG not null primary key,
	subdistrictId LONG,
	name VARCHAR(75) null,
	bnName VARCHAR(75) null,
	url VARCHAR(75) null,
	status VARCHAR(75) null,
	createdAt DATE null,
	updatedAt DATE null,
	geoCode LONG
);

create table dgf_renew_license (
	renewLicenseId LONG not null primary key,
	userId LONG,
	nationalId VARCHAR(75) null,
	licenseNo VARCHAR(75) null,
	licenseExpiryDate DATE null,
	tradeLicenseNo VARCHAR(75) null,
	tradeLicenseExpiryDate DATE null,
	tradeLicAttchId LONG,
	paymentAttchId LONG,
	applicationNo VARCHAR(75) null,
	licenseApplicationType VARCHAR(75) null,
	comments STRING null,
	createdDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null,
	fglPrePrimaryId LONG,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table dgf_store_dtls (
	id LONG not null primary key,
	national_id VARCHAR(75) null,
	type VARCHAR(75) null,
	mouza VARCHAR(75) null,
	khatiyn VARCHAR(75) null,
	dag_no VARCHAR(75) null,
	division LONG,
	district LONG,
	upzilla LONG,
	union_name LONG,
	city_corporatn LONG,
	dics_hight VARCHAR(75) null,
	dics_width VARCHAR(75) null,
	dics_lngth VARCHAR(75) null,
	dics_cpacty LONG,
	total_cpacty LONG,
	created_at DATE null,
	updated_at DATE null,
	flag INTEGER
);

create table dgf_user_otp_dtls (
	otpId LONG not null primary key,
	nationalId VARCHAR(75) null,
	otp LONG,
	otpRequestTime DATE null,
	otpLoginTime DATE null,
	otpExpireTime DATE null,
	userId LONG,
	userRegNo LONG,
	mobileNo VARCHAR(75) null,
	emailId VARCHAR(75) null,
	otpVerify VARCHAR(75) null,
	isSent BOOLEAN,
	message TEXT null,
	requestUrl TEXT null,
	responseData TEXT null,
	responseStatusCode INTEGER,
	responseResult VARCHAR(75) null
);

create table dgf_users (
	userId LONG not null primary key,
	nationalId VARCHAR(75) null,
	password_ VARCHAR(75) null,
	applicantName VARCHAR(75) null,
	fatherName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	motherName VARCHAR(75) null,
	gender VARCHAR(75) null,
	maritalStatus VARCHAR(75) null,
	birthDate DATE null,
	mobileNo VARCHAR(75) null,
	presentAddrId LONG,
	applcProfile VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table dgf_users_addr_dtls (
	addressId LONG not null primary key,
	nationalId LONG,
	classPk LONG,
	className VARCHAR(75) null,
	addressType VARCHAR(75) null,
	division LONG,
	district LONG,
	upzilla LONG,
	unionName LONG,
	village VARCHAR(75) null,
	ward VARCHAR(75) null,
	zipCode VARCHAR(75) null,
	postOffice VARCHAR(75) null,
	houseAddress VARCHAR(75) null,
	lastUpdatedDate DATE null,
	lastUpdatedBy DATE null
);

create table dgf_users_dtls (
	userDetailsId LONG not null primary key,
	nationalId LONG,
	email VARCHAR(75) null,
	nidPhotoAttchId LONG,
	nidDivision VARCHAR(75) null,
	nidDistrict VARCHAR(75) null,
	nidUpzilla VARCHAR(75) null,
	nidUnion VARCHAR(75) null,
	nidVillage VARCHAR(75) null,
	nidWard VARCHAR(75) null,
	nidZipCode VARCHAR(75) null,
	nidHouseAddress VARCHAR(75) null,
	lastUpdatedDate DATE null,
	nidPostOffice VARCHAR(75) null
);

create table dgf_users_fortnightreport_c (
	reportId LONG not null primary key,
	userId LONG,
	usernationalId VARCHAR(75) null,
	licenseNo VARCHAR(75) null,
	screenName VARCHAR(75) null,
	fullName VARCHAR(75) null,
	bussinessType VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	product VARCHAR(75) null,
	daterecipt DATE null,
	receivedQuantity INTEGER,
	receivedQuantityUnit VARCHAR(75) null,
	lastDateApprove DATE null,
	unsoldQuantity INTEGER,
	unsolddunit VARCHAR(75) null,
	reasonForBeingUnsold VARCHAR(75) null
);

create table dgf_users_fortnightreport_d (
	reportId LONG not null primary key,
	userId LONG,
	usernationalId VARCHAR(75) null,
	licenseNo VARCHAR(75) null,
	screenName VARCHAR(75) null,
	fullName VARCHAR(75) null,
	bussinessType VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	product VARCHAR(75) null,
	initalStockOn INTEGER,
	initalStockOnUnit VARCHAR(75) null,
	recivedQuantity INTEGER,
	recivedQuantityUnit VARCHAR(75) null,
	sellingQuantity INTEGER,
	sellingQuantityUnit VARCHAR(75) null,
	quantityOfFinishingStock INTEGER,
	quantityOfFinishingStockUnit VARCHAR(75) null,
	comment_ VARCHAR(75) null,
	nationalId VARCHAR(75) null
);

create table dgf_verified_beneficiaries (
	id LONG not null primary key,
	bsb_verified INTEGER,
	card_no LONG,
	created_at DATE null,
	date_of_birth VARCHAR(255) null,
	dealer_id LONG,
	district_id LONG,
	division_id LONG,
	ec_beneficiary_name VARCHAR(500) null,
	ec_beneficiary_name_en VARCHAR(500) null,
	ec_blood_group VARCHAR(500) null,
	ec_father_name VARCHAR(500) null,
	ec_gender VARCHAR(500) null,
	ec_mobile_no VARCHAR(500) null,
	ec_mother_name VARCHAR(500) null,
	ec_occupation VARCHAR(200) null,
	ec_pm_additional_mouza_moholla VARCHAR(290) null,
	ec_pm_additional_village_road VARCHAR(250) null,
	ec_pm_district VARCHAR(250) null,
	ec_pm_division VARCHAR(50) null,
	ec_pm_home_holding_no VARCHAR(250) null,
	ec_pm_mouza_moholla VARCHAR(250) null,
	ec_pm_postal_code VARCHAR(50) null,
	ec_pm_post_office VARCHAR(250) null,
	ec_pm_region VARCHAR(250) null,
	ec_pm_rmo VARCHAR(250) null,
	ec_pm_union_ward VARCHAR(250) null,
	ec_pm_upazila VARCHAR(250) null,
	ec_pm_village_road VARCHAR(250) null,
	ec_pm_ward_union_porishod VARCHAR(250) null,
	ec_pr_additional_mouza_moholla VARCHAR(299) null,
	ec_pr_additional_village_road VARCHAR(250) null,
	ec_pr_city_corp_municipality VARCHAR(250) null,
	ec_pr_district VARCHAR(250) null,
	ec_pr_division VARCHAR(250) null,
	ec_pr_home_holding_no VARCHAR(250) null,
	ec_pr_mouza_moholla VARCHAR(250) null,
	ec_pr_postal_code VARCHAR(50) null,
	ec_pr_post_office VARCHAR(250) null,
	ec_pr_region VARCHAR(200) null,
	ec_pr_rmo VARCHAR(250) null,
	ec_pr_union_ward VARCHAR(250) null,
	ec_pr_upazila VARCHAR(250) null,
	ec_pr_village_road VARCHAR(250) null,
	ec_pr_ward_union_porishod VARCHAR(250) null,
	ec_spouse_name VARCHAR(500) null,
	ec_verified INTEGER,
	final_status LONG,
	given_mobile_no VARCHAR(500) null,
	image_path_ec VARCHAR(500) null,
	image_path_real VARCHAR(500) null,
	national_id VARCHAR(100) null,
	new_card_number LONG,
	raw_data_id LONG,
	remarks VARCHAR(500) null,
	second_national_id VARCHAR(100) null,
	status LONG,
	ucf_verified_date DATE null,
	union_id LONG,
	upazila_id LONG,
	updated_at DATE null,
	verified_by LONG,
	verified_date DATE null,
	vgd_status INTEGER
);