/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.dealer.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfDlrUpdtTempDtls service. Represents a row in the &quot;dgf_dlr_updt_temp_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrUpdtTempDtlsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrUpdtTempDtlsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfDlrUpdtTempDtls
 * @generated
 */
@ProviderType
public interface DgfDlrUpdtTempDtlsModel
	extends BaseModel<DgfDlrUpdtTempDtls>, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf dlr updt temp dtls model instance should use the {@link DgfDlrUpdtTempDtls} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf dlr updt temp dtls.
	 *
	 * @return the primary key of this dgf dlr updt temp dtls
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf dlr updt temp dtls.
	 *
	 * @param primaryKey the primary key of this dgf dlr updt temp dtls
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dgf dlr update req ID of this dgf dlr updt temp dtls.
	 *
	 * @return the dgf dlr update req ID of this dgf dlr updt temp dtls
	 */
	public long getDgfDlrUpdateReqId();

	/**
	 * Sets the dgf dlr update req ID of this dgf dlr updt temp dtls.
	 *
	 * @param dgfDlrUpdateReqId the dgf dlr update req ID of this dgf dlr updt temp dtls
	 */
	public void setDgfDlrUpdateReqId(long dgfDlrUpdateReqId);

	/**
	 * Returns the national ID of this dgf dlr updt temp dtls.
	 *
	 * @return the national ID of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this dgf dlr updt temp dtls.
	 *
	 * @param nationalId the national ID of this dgf dlr updt temp dtls
	 */
	public void setNationalId(String nationalId);

	/**
	 * Returns the dlr reg no of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr reg no of this dgf dlr updt temp dtls
	 */
	public long getDlrRegNo();

	/**
	 * Sets the dlr reg no of this dgf dlr updt temp dtls.
	 *
	 * @param dlrRegNo the dlr reg no of this dgf dlr updt temp dtls
	 */
	public void setDlrRegNo(long dlrRegNo);

	/**
	 * Returns the marital status of this dgf dlr updt temp dtls.
	 *
	 * @return the marital status of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this dgf dlr updt temp dtls.
	 *
	 * @param maritalStatus the marital status of this dgf dlr updt temp dtls
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the spouse name of this dgf dlr updt temp dtls.
	 *
	 * @return the spouse name of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getSpouseName();

	/**
	 * Sets the spouse name of this dgf dlr updt temp dtls.
	 *
	 * @param spouseName the spouse name of this dgf dlr updt temp dtls
	 */
	public void setSpouseName(String spouseName);

	/**
	 * Returns the spouse fthr name of this dgf dlr updt temp dtls.
	 *
	 * @return the spouse fthr name of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getSpouseFthrName();

	/**
	 * Sets the spouse fthr name of this dgf dlr updt temp dtls.
	 *
	 * @param spouseFthrName the spouse fthr name of this dgf dlr updt temp dtls
	 */
	public void setSpouseFthrName(String spouseFthrName);

	/**
	 * Returns the spouse nid of this dgf dlr updt temp dtls.
	 *
	 * @return the spouse nid of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getSpouseNid();

	/**
	 * Sets the spouse nid of this dgf dlr updt temp dtls.
	 *
	 * @param spouseNid the spouse nid of this dgf dlr updt temp dtls
	 */
	public void setSpouseNid(String spouseNid);

	/**
	 * Returns the spouse brth date of this dgf dlr updt temp dtls.
	 *
	 * @return the spouse brth date of this dgf dlr updt temp dtls
	 */
	public Date getSpouseBrthDate();

	/**
	 * Sets the spouse brth date of this dgf dlr updt temp dtls.
	 *
	 * @param spouseBrthDate the spouse brth date of this dgf dlr updt temp dtls
	 */
	public void setSpouseBrthDate(Date spouseBrthDate);

	/**
	 * Returns the pblc rep of this dgf dlr updt temp dtls.
	 *
	 * @return the pblc rep of this dgf dlr updt temp dtls
	 */
	public int getPblcRep();

	/**
	 * Sets the pblc rep of this dgf dlr updt temp dtls.
	 *
	 * @param pblcRep the pblc rep of this dgf dlr updt temp dtls
	 */
	public void setPblcRep(int pblcRep);

	/**
	 * Returns the wrk in govt of this dgf dlr updt temp dtls.
	 *
	 * @return the wrk in govt of this dgf dlr updt temp dtls
	 */
	public int getWrkInGovt();

	/**
	 * Sets the wrk in govt of this dgf dlr updt temp dtls.
	 *
	 * @param wrkInGovt the wrk in govt of this dgf dlr updt temp dtls
	 */
	public void setWrkInGovt(int wrkInGovt);

	/**
	 * Returns the physcly chlngd of this dgf dlr updt temp dtls.
	 *
	 * @return the physcly chlngd of this dgf dlr updt temp dtls
	 */
	public int getPhysclyChlngd();

	/**
	 * Sets the physcly chlngd of this dgf dlr updt temp dtls.
	 *
	 * @param physclyChlngd the physcly chlngd of this dgf dlr updt temp dtls
	 */
	public void setPhysclyChlngd(int physclyChlngd);

	/**
	 * Returns the phscly chlngd attch ID of this dgf dlr updt temp dtls.
	 *
	 * @return the phscly chlngd attch ID of this dgf dlr updt temp dtls
	 */
	public long getPhsclyChlngdAttchId();

	/**
	 * Sets the phscly chlngd attch ID of this dgf dlr updt temp dtls.
	 *
	 * @param phsclyChlngdAttchId the phscly chlngd attch ID of this dgf dlr updt temp dtls
	 */
	public void setPhsclyChlngdAttchId(long phsclyChlngdAttchId);

	/**
	 * Returns the shp division of this dgf dlr updt temp dtls.
	 *
	 * @return the shp division of this dgf dlr updt temp dtls
	 */
	public long getShpDivision();

	/**
	 * Sets the shp division of this dgf dlr updt temp dtls.
	 *
	 * @param shpDivision the shp division of this dgf dlr updt temp dtls
	 */
	public void setShpDivision(long shpDivision);

	/**
	 * Returns the shp district of this dgf dlr updt temp dtls.
	 *
	 * @return the shp district of this dgf dlr updt temp dtls
	 */
	public long getShpDistrict();

	/**
	 * Sets the shp district of this dgf dlr updt temp dtls.
	 *
	 * @param shpDistrict the shp district of this dgf dlr updt temp dtls
	 */
	public void setShpDistrict(long shpDistrict);

	/**
	 * Returns the shp upzilla of this dgf dlr updt temp dtls.
	 *
	 * @return the shp upzilla of this dgf dlr updt temp dtls
	 */
	public long getShpUpzilla();

	/**
	 * Sets the shp upzilla of this dgf dlr updt temp dtls.
	 *
	 * @param shpUpzilla the shp upzilla of this dgf dlr updt temp dtls
	 */
	public void setShpUpzilla(long shpUpzilla);

	/**
	 * Returns the shp union of this dgf dlr updt temp dtls.
	 *
	 * @return the shp union of this dgf dlr updt temp dtls
	 */
	public long getShpUnion();

	/**
	 * Sets the shp union of this dgf dlr updt temp dtls.
	 *
	 * @param shpUnion the shp union of this dgf dlr updt temp dtls
	 */
	public void setShpUnion(long shpUnion);

	/**
	 * Returns the shp village of this dgf dlr updt temp dtls.
	 *
	 * @return the shp village of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpVillage();

	/**
	 * Sets the shp village of this dgf dlr updt temp dtls.
	 *
	 * @param shpVillage the shp village of this dgf dlr updt temp dtls
	 */
	public void setShpVillage(String shpVillage);

	/**
	 * Returns the shp ward of this dgf dlr updt temp dtls.
	 *
	 * @return the shp ward of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpWard();

	/**
	 * Sets the shp ward of this dgf dlr updt temp dtls.
	 *
	 * @param shpWard the shp ward of this dgf dlr updt temp dtls
	 */
	public void setShpWard(String shpWard);

	/**
	 * Returns the shp zip code of this dgf dlr updt temp dtls.
	 *
	 * @return the shp zip code of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpZipCode();

	/**
	 * Sets the shp zip code of this dgf dlr updt temp dtls.
	 *
	 * @param shpZipCode the shp zip code of this dgf dlr updt temp dtls
	 */
	public void setShpZipCode(String shpZipCode);

	/**
	 * Returns the shp pst offc of this dgf dlr updt temp dtls.
	 *
	 * @return the shp pst offc of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpPstOffc();

	/**
	 * Sets the shp pst offc of this dgf dlr updt temp dtls.
	 *
	 * @param shpPstOffc the shp pst offc of this dgf dlr updt temp dtls
	 */
	public void setShpPstOffc(String shpPstOffc);

	/**
	 * Returns the shp present address of this dgf dlr updt temp dtls.
	 *
	 * @return the shp present address of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpPresentAddress();

	/**
	 * Sets the shp present address of this dgf dlr updt temp dtls.
	 *
	 * @param shpPresentAddress the shp present address of this dgf dlr updt temp dtls
	 */
	public void setShpPresentAddress(String shpPresentAddress);

	/**
	 * Returns the shp location of this dgf dlr updt temp dtls.
	 *
	 * @return the shp location of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getShpLocation();

	/**
	 * Sets the shp location of this dgf dlr updt temp dtls.
	 *
	 * @param shpLocation the shp location of this dgf dlr updt temp dtls
	 */
	public void setShpLocation(String shpLocation);

	/**
	 * Returns the shp length of this dgf dlr updt temp dtls.
	 *
	 * @return the shp length of this dgf dlr updt temp dtls
	 */
	public long getShpLength();

	/**
	 * Sets the shp length of this dgf dlr updt temp dtls.
	 *
	 * @param shpLength the shp length of this dgf dlr updt temp dtls
	 */
	public void setShpLength(long shpLength);

	/**
	 * Returns the shp height of this dgf dlr updt temp dtls.
	 *
	 * @return the shp height of this dgf dlr updt temp dtls
	 */
	public long getShpHeight();

	/**
	 * Sets the shp height of this dgf dlr updt temp dtls.
	 *
	 * @param shpHeight the shp height of this dgf dlr updt temp dtls
	 */
	public void setShpHeight(long shpHeight);

	/**
	 * Returns the shp width of this dgf dlr updt temp dtls.
	 *
	 * @return the shp width of this dgf dlr updt temp dtls
	 */
	public long getShpWidth();

	/**
	 * Sets the shp width of this dgf dlr updt temp dtls.
	 *
	 * @param shpWidth the shp width of this dgf dlr updt temp dtls
	 */
	public void setShpWidth(long shpWidth);

	/**
	 * Returns the shp strg cpcty of this dgf dlr updt temp dtls.
	 *
	 * @return the shp strg cpcty of this dgf dlr updt temp dtls
	 */
	public long getShpStrgCpcty();

	/**
	 * Sets the shp strg cpcty of this dgf dlr updt temp dtls.
	 *
	 * @param shpStrgCpcty the shp strg cpcty of this dgf dlr updt temp dtls
	 */
	public void setShpStrgCpcty(long shpStrgCpcty);

	/**
	 * Returns the shp flr cmntd of this dgf dlr updt temp dtls.
	 *
	 * @return the shp flr cmntd of this dgf dlr updt temp dtls
	 */
	public int getShpFlrCmntd();

	/**
	 * Sets the shp flr cmntd of this dgf dlr updt temp dtls.
	 *
	 * @param shpFlrCmntd the shp flr cmntd of this dgf dlr updt temp dtls
	 */
	public void setShpFlrCmntd(int shpFlrCmntd);

	/**
	 * Returns the shp sign brd of this dgf dlr updt temp dtls.
	 *
	 * @return the shp sign brd of this dgf dlr updt temp dtls
	 */
	public int getShpSignBrd();

	/**
	 * Sets the shp sign brd of this dgf dlr updt temp dtls.
	 *
	 * @param shpSignBrd the shp sign brd of this dgf dlr updt temp dtls
	 */
	public void setShpSignBrd(int shpSignBrd);

	/**
	 * Returns the license type of this dgf dlr updt temp dtls.
	 *
	 * @return the license type of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getLicenseType();

	/**
	 * Sets the license type of this dgf dlr updt temp dtls.
	 *
	 * @param licenseType the license type of this dgf dlr updt temp dtls
	 */
	public void setLicenseType(String licenseType);

	/**
	 * Returns the thrd party ops flg of this dgf dlr updt temp dtls.
	 *
	 * @return the thrd party ops flg of this dgf dlr updt temp dtls
	 */
	public long getThrdPartyOpsFlg();

	/**
	 * Sets the thrd party ops flg of this dgf dlr updt temp dtls.
	 *
	 * @param thrdPartyOpsFlg the thrd party ops flg of this dgf dlr updt temp dtls
	 */
	public void setThrdPartyOpsFlg(long thrdPartyOpsFlg);

	/**
	 * Returns the dlrshp fmly mmbr name of this dgf dlr updt temp dtls.
	 *
	 * @return the dlrshp fmly mmbr name of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrshpFmlyMmbrName();

	/**
	 * Sets the dlrshp fmly mmbr name of this dgf dlr updt temp dtls.
	 *
	 * @param dlrshpFmlyMmbrName the dlrshp fmly mmbr name of this dgf dlr updt temp dtls
	 */
	public void setDlrshpFmlyMmbrName(String dlrshpFmlyMmbrName);

	/**
	 * Returns the dlrshp fmly mmbr type of this dgf dlr updt temp dtls.
	 *
	 * @return the dlrshp fmly mmbr type of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrshpFmlyMmbrType();

	/**
	 * Sets the dlrshp fmly mmbr type of this dgf dlr updt temp dtls.
	 *
	 * @param dlrshpFmlyMmbrType the dlrshp fmly mmbr type of this dgf dlr updt temp dtls
	 */
	public void setDlrshpFmlyMmbrType(String dlrshpFmlyMmbrType);

	/**
	 * Returns the dlr perf yr1 of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr1 of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr1();

	/**
	 * Sets the dlr perf yr1 of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr1 the dlr perf yr1 of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr1(long dlrPerfYr1);

	/**
	 * Returns the dlr perf yr1 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr1 alloc qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr1AllocQty();

	/**
	 * Sets the dlr perf yr1 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr1AllocQty the dlr perf yr1 alloc qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr1AllocQty(long dlrPerfYr1AllocQty);

	/**
	 * Returns the dlr perf yr1 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr1 comdty qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr1ComdtyQty();

	/**
	 * Sets the dlr perf yr1 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr1ComdtyQty the dlr perf yr1 comdty qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr1ComdtyQty(long dlrPerfYr1ComdtyQty);

	/**
	 * Returns the dlr perf yr1 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr1 dlr ctgry of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr1DlrCtgry();

	/**
	 * Sets the dlr perf yr1 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr1DlrCtgry the dlr perf yr1 dlr ctgry of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr1DlrCtgry(String dlrPerfYr1DlrCtgry);

	/**
	 * Returns the dlr perf yr1 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr1 rmrk of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr1Rmrk();

	/**
	 * Sets the dlr perf yr1 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr1Rmrk the dlr perf yr1 rmrk of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr1Rmrk(String dlrPerfYr1Rmrk);

	/**
	 * Returns the dlr perf yr2 of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr2 of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr2();

	/**
	 * Sets the dlr perf yr2 of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr2 the dlr perf yr2 of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr2(long dlrPerfYr2);

	/**
	 * Returns the dlr perf yr2 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr2 alloc qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr2AllocQty();

	/**
	 * Sets the dlr perf yr2 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr2AllocQty the dlr perf yr2 alloc qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr2AllocQty(long dlrPerfYr2AllocQty);

	/**
	 * Returns the dlr perf yr2 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr2 comdty qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr2ComdtyQty();

	/**
	 * Sets the dlr perf yr2 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr2ComdtyQty the dlr perf yr2 comdty qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr2ComdtyQty(long dlrPerfYr2ComdtyQty);

	/**
	 * Returns the dlr perf yr2 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr2 dlr ctgry of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr2DlrCtgry();

	/**
	 * Sets the dlr perf yr2 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr2DlrCtgry the dlr perf yr2 dlr ctgry of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr2DlrCtgry(String dlrPerfYr2DlrCtgry);

	/**
	 * Returns the dlr perf yr2 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr2 rmrk of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr2Rmrk();

	/**
	 * Sets the dlr perf yr2 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr2Rmrk the dlr perf yr2 rmrk of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr2Rmrk(String dlrPerfYr2Rmrk);

	/**
	 * Returns the dlr perf yr3 of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr3 of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr3();

	/**
	 * Sets the dlr perf yr3 of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr3 the dlr perf yr3 of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr3(long dlrPerfYr3);

	/**
	 * Returns the dlr perf yr3 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr3 alloc qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr3AllocQty();

	/**
	 * Sets the dlr perf yr3 alloc qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr3AllocQty the dlr perf yr3 alloc qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr3AllocQty(long dlrPerfYr3AllocQty);

	/**
	 * Returns the dlr perf yr3 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr3 comdty qty of this dgf dlr updt temp dtls
	 */
	public long getDlrPerfYr3ComdtyQty();

	/**
	 * Sets the dlr perf yr3 comdty qty of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr3ComdtyQty the dlr perf yr3 comdty qty of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr3ComdtyQty(long dlrPerfYr3ComdtyQty);

	/**
	 * Returns the dlr perf yr3 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr3 dlr ctgry of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr3DlrCtgry();

	/**
	 * Sets the dlr perf yr3 dlr ctgry of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr3DlrCtgry the dlr perf yr3 dlr ctgry of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr3DlrCtgry(String dlrPerfYr3DlrCtgry);

	/**
	 * Returns the dlr perf yr3 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr perf yr3 rmrk of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrPerfYr3Rmrk();

	/**
	 * Sets the dlr perf yr3 rmrk of this dgf dlr updt temp dtls.
	 *
	 * @param dlrPerfYr3Rmrk the dlr perf yr3 rmrk of this dgf dlr updt temp dtls
	 */
	public void setDlrPerfYr3Rmrk(String dlrPerfYr3Rmrk);

	/**
	 * Returns the trck licns plat no of this dgf dlr updt temp dtls.
	 *
	 * @return the trck licns plat no of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getTrckLicnsPlatNo();

	/**
	 * Sets the trck licns plat no of this dgf dlr updt temp dtls.
	 *
	 * @param trckLicnsPlatNo the trck licns plat no of this dgf dlr updt temp dtls
	 */
	public void setTrckLicnsPlatNo(String trckLicnsPlatNo);

	/**
	 * Returns the trck cpcty of this dgf dlr updt temp dtls.
	 *
	 * @return the trck cpcty of this dgf dlr updt temp dtls
	 */
	public long getTrckCpcty();

	/**
	 * Sets the trck cpcty of this dgf dlr updt temp dtls.
	 *
	 * @param trckCpcty the trck cpcty of this dgf dlr updt temp dtls
	 */
	public void setTrckCpcty(long trckCpcty);

	/**
	 * Returns the trck make of this dgf dlr updt temp dtls.
	 *
	 * @return the trck make of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getTrckMake();

	/**
	 * Sets the trck make of this dgf dlr updt temp dtls.
	 *
	 * @param trckMake the trck make of this dgf dlr updt temp dtls
	 */
	public void setTrckMake(String trckMake);

	/**
	 * Returns the trck model of this dgf dlr updt temp dtls.
	 *
	 * @return the trck model of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getTrckModel();

	/**
	 * Sets the trck model of this dgf dlr updt temp dtls.
	 *
	 * @param trckModel the trck model of this dgf dlr updt temp dtls
	 */
	public void setTrckModel(String trckModel);

	/**
	 * Returns the trck rent own flg of this dgf dlr updt temp dtls.
	 *
	 * @return the trck rent own flg of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getTrckRentOwnFlg();

	/**
	 * Sets the trck rent own flg of this dgf dlr updt temp dtls.
	 *
	 * @param trckRentOwnFlg the trck rent own flg of this dgf dlr updt temp dtls
	 */
	public void setTrckRentOwnFlg(String trckRentOwnFlg);

	/**
	 * Returns the trck mfg yr of this dgf dlr updt temp dtls.
	 *
	 * @return the trck mfg yr of this dgf dlr updt temp dtls
	 */
	public long getTrckMfgYr();

	/**
	 * Sets the trck mfg yr of this dgf dlr updt temp dtls.
	 *
	 * @param trckMfgYr the trck mfg yr of this dgf dlr updt temp dtls
	 */
	public void setTrckMfgYr(long trckMfgYr);

	/**
	 * Returns the version of this dgf dlr updt temp dtls.
	 *
	 * @return the version of this dgf dlr updt temp dtls
	 */
	public long getVersion();

	/**
	 * Sets the version of this dgf dlr updt temp dtls.
	 *
	 * @param version the version of this dgf dlr updt temp dtls
	 */
	public void setVersion(long version);

	/**
	 * Returns the status of this dgf dlr updt temp dtls.
	 *
	 * @return the status of this dgf dlr updt temp dtls
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this dgf dlr updt temp dtls.
	 *
	 * @param status the status of this dgf dlr updt temp dtls
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this dgf dlr updt temp dtls.
	 *
	 * @return the status by user ID of this dgf dlr updt temp dtls
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this dgf dlr updt temp dtls.
	 *
	 * @param statusByUserId the status by user ID of this dgf dlr updt temp dtls
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this dgf dlr updt temp dtls.
	 *
	 * @return the status by user uuid of this dgf dlr updt temp dtls
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this dgf dlr updt temp dtls.
	 *
	 * @param statusByUserUuid the status by user uuid of this dgf dlr updt temp dtls
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this dgf dlr updt temp dtls.
	 *
	 * @return the status by user name of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this dgf dlr updt temp dtls.
	 *
	 * @param statusByUserName the status by user name of this dgf dlr updt temp dtls
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this dgf dlr updt temp dtls.
	 *
	 * @return the status date of this dgf dlr updt temp dtls
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this dgf dlr updt temp dtls.
	 *
	 * @param statusDate the status date of this dgf dlr updt temp dtls
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the create date of this dgf dlr updt temp dtls.
	 *
	 * @return the create date of this dgf dlr updt temp dtls
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dgf dlr updt temp dtls.
	 *
	 * @param createDate the create date of this dgf dlr updt temp dtls
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the last updtd by of this dgf dlr updt temp dtls.
	 *
	 * @return the last updtd by of this dgf dlr updt temp dtls
	 */
	public long getLastUpdtdBy();

	/**
	 * Sets the last updtd by of this dgf dlr updt temp dtls.
	 *
	 * @param lastUpdtdBy the last updtd by of this dgf dlr updt temp dtls
	 */
	public void setLastUpdtdBy(long lastUpdtdBy);

	/**
	 * Returns the modified date of this dgf dlr updt temp dtls.
	 *
	 * @return the modified date of this dgf dlr updt temp dtls
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dgf dlr updt temp dtls.
	 *
	 * @param modifiedDate the modified date of this dgf dlr updt temp dtls
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the foodgrain license of this dgf dlr updt temp dtls.
	 *
	 * @return the foodgrain license of this dgf dlr updt temp dtls
	 */
	public int getFoodgrainLicense();

	/**
	 * Sets the foodgrain license of this dgf dlr updt temp dtls.
	 *
	 * @param foodgrainLicense the foodgrain license of this dgf dlr updt temp dtls
	 */
	public void setFoodgrainLicense(int foodgrainLicense);

	/**
	 * Returns the trade license of this dgf dlr updt temp dtls.
	 *
	 * @return the trade license of this dgf dlr updt temp dtls
	 */
	public int getTradeLicense();

	/**
	 * Sets the trade license of this dgf dlr updt temp dtls.
	 *
	 * @param tradeLicense the trade license of this dgf dlr updt temp dtls
	 */
	public void setTradeLicense(int tradeLicense);

	/**
	 * Returns the tcv dlr license of this dgf dlr updt temp dtls.
	 *
	 * @return the tcv dlr license of this dgf dlr updt temp dtls
	 */
	public int getTcvDlrLicense();

	/**
	 * Sets the tcv dlr license of this dgf dlr updt temp dtls.
	 *
	 * @param tcvDlrLicense the tcv dlr license of this dgf dlr updt temp dtls
	 */
	public void setTcvDlrLicense(int tcvDlrLicense);

	/**
	 * Returns the import license of this dgf dlr updt temp dtls.
	 *
	 * @return the import license of this dgf dlr updt temp dtls
	 */
	public int getImportLicense();

	/**
	 * Sets the import license of this dgf dlr updt temp dtls.
	 *
	 * @param importLicense the import license of this dgf dlr updt temp dtls
	 */
	public void setImportLicense(int importLicense);

	/**
	 * Returns the license essential goods of this dgf dlr updt temp dtls.
	 *
	 * @return the license essential goods of this dgf dlr updt temp dtls
	 */
	public int getLicenseEssentialGoods();

	/**
	 * Sets the license essential goods of this dgf dlr updt temp dtls.
	 *
	 * @param licenseEssentialGoods the license essential goods of this dgf dlr updt temp dtls
	 */
	public void setLicenseEssentialGoods(int licenseEssentialGoods);

	/**
	 * Returns the trade license agriculture of this dgf dlr updt temp dtls.
	 *
	 * @return the trade license agriculture of this dgf dlr updt temp dtls
	 */
	public int getTradeLicenseAgriculture();

	/**
	 * Sets the trade license agriculture of this dgf dlr updt temp dtls.
	 *
	 * @param tradeLicenseAgriculture the trade license agriculture of this dgf dlr updt temp dtls
	 */
	public void setTradeLicenseAgriculture(int tradeLicenseAgriculture);

	/**
	 * Returns the dlr oms sub type of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr oms sub type of this dgf dlr updt temp dtls
	 */
	@AutoEscape
	public String getDlrOmsSubType();

	/**
	 * Sets the dlr oms sub type of this dgf dlr updt temp dtls.
	 *
	 * @param dlrOmsSubType the dlr oms sub type of this dgf dlr updt temp dtls
	 */
	public void setDlrOmsSubType(String dlrOmsSubType);

	/**
	 * Returns the user ID of this dgf dlr updt temp dtls.
	 *
	 * @return the user ID of this dgf dlr updt temp dtls
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dgf dlr updt temp dtls.
	 *
	 * @param userId the user ID of this dgf dlr updt temp dtls
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dgf dlr updt temp dtls.
	 *
	 * @return the user uuid of this dgf dlr updt temp dtls
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dgf dlr updt temp dtls.
	 *
	 * @param userUuid the user uuid of this dgf dlr updt temp dtls
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this dgf dlr updt temp dtls.
	 *
	 * @return the group ID of this dgf dlr updt temp dtls
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dgf dlr updt temp dtls.
	 *
	 * @param groupId the group ID of this dgf dlr updt temp dtls
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dgf dlr updt temp dtls.
	 *
	 * @return the company ID of this dgf dlr updt temp dtls
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dgf dlr updt temp dtls.
	 *
	 * @param companyId the company ID of this dgf dlr updt temp dtls
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the dlr run shp himself of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr run shp himself of this dgf dlr updt temp dtls
	 */
	public int getDlrRunShpHimself();

	/**
	 * Sets the dlr run shp himself of this dgf dlr updt temp dtls.
	 *
	 * @param dlrRunShpHimself the dlr run shp himself of this dgf dlr updt temp dtls
	 */
	public void setDlrRunShpHimself(int dlrRunShpHimself);

	/**
	 * Returns the dlr shp trck typ flg of this dgf dlr updt temp dtls.
	 *
	 * @return the dlr shp trck typ flg of this dgf dlr updt temp dtls
	 */
	public int getDlrShpTrckTypFlg();

	/**
	 * Sets the dlr shp trck typ flg of this dgf dlr updt temp dtls.
	 *
	 * @param dlrShpTrckTypFlg the dlr shp trck typ flg of this dgf dlr updt temp dtls
	 */
	public void setDlrShpTrckTypFlg(int dlrShpTrckTypFlg);

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is approved.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is denied.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is a draft.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is expired.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is inactive.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is incomplete.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is pending.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this dgf dlr updt temp dtls is scheduled.
	 *
	 * @return <code>true</code> if this dgf dlr updt temp dtls is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public DgfDlrUpdtTempDtls cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}