/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.dealer.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfDlrRegDtls service. Represents a row in the &quot;dgf_dlr_reg_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrRegDtlsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrRegDtlsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfDlrRegDtls
 * @generated
 */
@ProviderType
public interface DgfDlrRegDtlsModel
	extends BaseModel<DgfDlrRegDtls>, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf dlr reg dtls model instance should use the {@link DgfDlrRegDtls} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf dlr reg dtls.
	 *
	 * @return the primary key of this dgf dlr reg dtls
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf dlr reg dtls.
	 *
	 * @param primaryKey the primary key of this dgf dlr reg dtls
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dlr reg no of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg no of this dgf dlr reg dtls
	 */
	public long getDlrRegNo();

	/**
	 * Sets the dlr reg no of this dgf dlr reg dtls.
	 *
	 * @param dlrRegNo the dlr reg no of this dgf dlr reg dtls
	 */
	public void setDlrRegNo(long dlrRegNo);

	/**
	 * Returns the national ID of this dgf dlr reg dtls.
	 *
	 * @return the national ID of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this dgf dlr reg dtls.
	 *
	 * @param nationalId the national ID of this dgf dlr reg dtls
	 */
	public void setNationalId(String nationalId);

	/**
	 * Returns the user ID of this dgf dlr reg dtls.
	 *
	 * @return the user ID of this dgf dlr reg dtls
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dgf dlr reg dtls.
	 *
	 * @param userId the user ID of this dgf dlr reg dtls
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dgf dlr reg dtls.
	 *
	 * @return the user uuid of this dgf dlr reg dtls
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dgf dlr reg dtls.
	 *
	 * @param userUuid the user uuid of this dgf dlr reg dtls
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this dgf dlr reg dtls.
	 *
	 * @return the group ID of this dgf dlr reg dtls
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dgf dlr reg dtls.
	 *
	 * @param groupId the group ID of this dgf dlr reg dtls
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dgf dlr reg dtls.
	 *
	 * @return the company ID of this dgf dlr reg dtls
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dgf dlr reg dtls.
	 *
	 * @param companyId the company ID of this dgf dlr reg dtls
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the dlr reg appl no of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg appl no of this dgf dlr reg dtls
	 */
	public long getDlrRegApplNo();

	/**
	 * Sets the dlr reg appl no of this dgf dlr reg dtls.
	 *
	 * @param dlrRegApplNo the dlr reg appl no of this dgf dlr reg dtls
	 */
	public void setDlrRegApplNo(long dlrRegApplNo);

	/**
	 * Returns the fgl licns no of this dgf dlr reg dtls.
	 *
	 * @return the fgl licns no of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getFglLicnsNo();

	/**
	 * Sets the fgl licns no of this dgf dlr reg dtls.
	 *
	 * @param fglLicnsNo the fgl licns no of this dgf dlr reg dtls
	 */
	public void setFglLicnsNo(String fglLicnsNo);

	/**
	 * Returns the fgl licns issue date of this dgf dlr reg dtls.
	 *
	 * @return the fgl licns issue date of this dgf dlr reg dtls
	 */
	public Date getFglLicnsIssueDate();

	/**
	 * Sets the fgl licns issue date of this dgf dlr reg dtls.
	 *
	 * @param fglLicnsIssueDate the fgl licns issue date of this dgf dlr reg dtls
	 */
	public void setFglLicnsIssueDate(Date fglLicnsIssueDate);

	/**
	 * Returns the trd licns no of this dgf dlr reg dtls.
	 *
	 * @return the trd licns no of this dgf dlr reg dtls
	 */
	public long getTrdLicnsNo();

	/**
	 * Sets the trd licns no of this dgf dlr reg dtls.
	 *
	 * @param trdLicnsNo the trd licns no of this dgf dlr reg dtls
	 */
	public void setTrdLicnsNo(long trdLicnsNo);

	/**
	 * Returns the trd licns exp date of this dgf dlr reg dtls.
	 *
	 * @return the trd licns exp date of this dgf dlr reg dtls
	 */
	public Date getTrdLicnsExpDate();

	/**
	 * Sets the trd licns exp date of this dgf dlr reg dtls.
	 *
	 * @param trdLicnsExpDate the trd licns exp date of this dgf dlr reg dtls
	 */
	public void setTrdLicnsExpDate(Date trdLicnsExpDate);

	/**
	 * Returns the dlr type ID of this dgf dlr reg dtls.
	 *
	 * @return the dlr type ID of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrTypeId();

	/**
	 * Sets the dlr type ID of this dgf dlr reg dtls.
	 *
	 * @param dlrTypeId the dlr type ID of this dgf dlr reg dtls
	 */
	public void setDlrTypeId(String dlrTypeId);

	/**
	 * Returns the marital status of this dgf dlr reg dtls.
	 *
	 * @return the marital status of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this dgf dlr reg dtls.
	 *
	 * @param maritalStatus the marital status of this dgf dlr reg dtls
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the spouse name of this dgf dlr reg dtls.
	 *
	 * @return the spouse name of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getSpouseName();

	/**
	 * Sets the spouse name of this dgf dlr reg dtls.
	 *
	 * @param spouseName the spouse name of this dgf dlr reg dtls
	 */
	public void setSpouseName(String spouseName);

	/**
	 * Returns the spouse fthr name of this dgf dlr reg dtls.
	 *
	 * @return the spouse fthr name of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getSpouseFthrName();

	/**
	 * Sets the spouse fthr name of this dgf dlr reg dtls.
	 *
	 * @param spouseFthrName the spouse fthr name of this dgf dlr reg dtls
	 */
	public void setSpouseFthrName(String spouseFthrName);

	/**
	 * Returns the spouse nid of this dgf dlr reg dtls.
	 *
	 * @return the spouse nid of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getSpouseNid();

	/**
	 * Sets the spouse nid of this dgf dlr reg dtls.
	 *
	 * @param spouseNid the spouse nid of this dgf dlr reg dtls
	 */
	public void setSpouseNid(String spouseNid);

	/**
	 * Returns the spouse brth date of this dgf dlr reg dtls.
	 *
	 * @return the spouse brth date of this dgf dlr reg dtls
	 */
	public Date getSpouseBrthDate();

	/**
	 * Sets the spouse brth date of this dgf dlr reg dtls.
	 *
	 * @param spouseBrthDate the spouse brth date of this dgf dlr reg dtls
	 */
	public void setSpouseBrthDate(Date spouseBrthDate);

	/**
	 * Returns the dlr reg expiry date of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg expiry date of this dgf dlr reg dtls
	 */
	public Date getDlrRegExpiryDate();

	/**
	 * Sets the dlr reg expiry date of this dgf dlr reg dtls.
	 *
	 * @param dlrRegExpiryDate the dlr reg expiry date of this dgf dlr reg dtls
	 */
	public void setDlrRegExpiryDate(Date dlrRegExpiryDate);

	/**
	 * Returns the sap bu code of this dgf dlr reg dtls.
	 *
	 * @return the sap bu code of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getSapBuCode();

	/**
	 * Sets the sap bu code of this dgf dlr reg dtls.
	 *
	 * @param sapBuCode the sap bu code of this dgf dlr reg dtls
	 */
	public void setSapBuCode(String sapBuCode);

	/**
	 * Returns the dlr reg appl status of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg appl status of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrRegApplStatus();

	/**
	 * Sets the dlr reg appl status of this dgf dlr reg dtls.
	 *
	 * @param dlrRegApplStatus the dlr reg appl status of this dgf dlr reg dtls
	 */
	public void setDlrRegApplStatus(String dlrRegApplStatus);

	/**
	 * Returns the dlr reg crtd date of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg crtd date of this dgf dlr reg dtls
	 */
	public Date getDlrRegCrtdDate();

	/**
	 * Sets the dlr reg crtd date of this dgf dlr reg dtls.
	 *
	 * @param dlrRegCrtdDate the dlr reg crtd date of this dgf dlr reg dtls
	 */
	public void setDlrRegCrtdDate(Date dlrRegCrtdDate);

	/**
	 * Returns the pymnt trn ref no of this dgf dlr reg dtls.
	 *
	 * @return the pymnt trn ref no of this dgf dlr reg dtls
	 */
	public long getPymntTrnRefNo();

	/**
	 * Sets the pymnt trn ref no of this dgf dlr reg dtls.
	 *
	 * @param pymntTrnRefNo the pymnt trn ref no of this dgf dlr reg dtls
	 */
	public void setPymntTrnRefNo(long pymntTrnRefNo);

	/**
	 * Returns the pymnt trn status of this dgf dlr reg dtls.
	 *
	 * @return the pymnt trn status of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getPymntTrnStatus();

	/**
	 * Sets the pymnt trn status of this dgf dlr reg dtls.
	 *
	 * @param pymntTrnStatus the pymnt trn status of this dgf dlr reg dtls
	 */
	public void setPymntTrnStatus(String pymntTrnStatus);

	/**
	 * Returns the challan doc ID of this dgf dlr reg dtls.
	 *
	 * @return the challan doc ID of this dgf dlr reg dtls
	 */
	public long getChallanDocId();

	/**
	 * Sets the challan doc ID of this dgf dlr reg dtls.
	 *
	 * @param challanDocId the challan doc ID of this dgf dlr reg dtls
	 */
	public void setChallanDocId(long challanDocId);

	/**
	 * Returns the incm tax attch ID of this dgf dlr reg dtls.
	 *
	 * @return the incm tax attch ID of this dgf dlr reg dtls
	 */
	public long getIncmTaxAttchID();

	/**
	 * Sets the incm tax attch ID of this dgf dlr reg dtls.
	 *
	 * @param incmTaxAttchID the incm tax attch ID of this dgf dlr reg dtls
	 */
	public void setIncmTaxAttchID(long incmTaxAttchID);

	/**
	 * Returns the bnk solvncy cert ID of this dgf dlr reg dtls.
	 *
	 * @return the bnk solvncy cert ID of this dgf dlr reg dtls
	 */
	public long getBnkSolvncyCertId();

	/**
	 * Sets the bnk solvncy cert ID of this dgf dlr reg dtls.
	 *
	 * @param bnkSolvncyCertId the bnk solvncy cert ID of this dgf dlr reg dtls
	 */
	public void setBnkSolvncyCertId(long bnkSolvncyCertId);

	/**
	 * Returns the shp ownship docu ID of this dgf dlr reg dtls.
	 *
	 * @return the shp ownship docu ID of this dgf dlr reg dtls
	 */
	public long getShpOwnshipDocuId();

	/**
	 * Sets the shp ownship docu ID of this dgf dlr reg dtls.
	 *
	 * @param shpOwnshipDocuId the shp ownship docu ID of this dgf dlr reg dtls
	 */
	public void setShpOwnshipDocuId(long shpOwnshipDocuId);

	/**
	 * Returns the shp rented docu ID of this dgf dlr reg dtls.
	 *
	 * @return the shp rented docu ID of this dgf dlr reg dtls
	 */
	public long getShpRentedDocuId();

	/**
	 * Sets the shp rented docu ID of this dgf dlr reg dtls.
	 *
	 * @param shpRentedDocuId the shp rented docu ID of this dgf dlr reg dtls
	 */
	public void setShpRentedDocuId(long shpRentedDocuId);

	/**
	 * Returns the signature ID of this dgf dlr reg dtls.
	 *
	 * @return the signature ID of this dgf dlr reg dtls
	 */
	public long getSignatureId();

	/**
	 * Sets the signature ID of this dgf dlr reg dtls.
	 *
	 * @param signatureId the signature ID of this dgf dlr reg dtls
	 */
	public void setSignatureId(long signatureId);

	/**
	 * Returns the dlr appr rjct comments of this dgf dlr reg dtls.
	 *
	 * @return the dlr appr rjct comments of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrApprRjctComments();

	/**
	 * Sets the dlr appr rjct comments of this dgf dlr reg dtls.
	 *
	 * @param dlrApprRjctComments the dlr appr rjct comments of this dgf dlr reg dtls
	 */
	public void setDlrApprRjctComments(String dlrApprRjctComments);

	/**
	 * Returns the dlr reg appr rej rmrk of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg appr rej rmrk of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrRegApprRejRmrk();

	/**
	 * Sets the dlr reg appr rej rmrk of this dgf dlr reg dtls.
	 *
	 * @param dlrRegApprRejRmrk the dlr reg appr rej rmrk of this dgf dlr reg dtls
	 */
	public void setDlrRegApprRejRmrk(String dlrRegApprRejRmrk);

	/**
	 * Returns the status of this dgf dlr reg dtls.
	 *
	 * @return the status of this dgf dlr reg dtls
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this dgf dlr reg dtls.
	 *
	 * @param status the status of this dgf dlr reg dtls
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this dgf dlr reg dtls.
	 *
	 * @return the status by user ID of this dgf dlr reg dtls
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this dgf dlr reg dtls.
	 *
	 * @param statusByUserId the status by user ID of this dgf dlr reg dtls
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this dgf dlr reg dtls.
	 *
	 * @return the status by user uuid of this dgf dlr reg dtls
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this dgf dlr reg dtls.
	 *
	 * @param statusByUserUuid the status by user uuid of this dgf dlr reg dtls
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this dgf dlr reg dtls.
	 *
	 * @return the status by user name of this dgf dlr reg dtls
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this dgf dlr reg dtls.
	 *
	 * @param statusByUserName the status by user name of this dgf dlr reg dtls
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this dgf dlr reg dtls.
	 *
	 * @return the status date of this dgf dlr reg dtls
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this dgf dlr reg dtls.
	 *
	 * @param statusDate the status date of this dgf dlr reg dtls
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the version of this dgf dlr reg dtls.
	 *
	 * @return the version of this dgf dlr reg dtls
	 */
	public long getVersion();

	/**
	 * Sets the version of this dgf dlr reg dtls.
	 *
	 * @param version the version of this dgf dlr reg dtls
	 */
	public void setVersion(long version);

	/**
	 * Returns the dlr reg crtd by of this dgf dlr reg dtls.
	 *
	 * @return the dlr reg crtd by of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrRegCrtdBy();

	/**
	 * Sets the dlr reg crtd by of this dgf dlr reg dtls.
	 *
	 * @param dlrRegCrtdBy the dlr reg crtd by of this dgf dlr reg dtls
	 */
	public void setDlrRegCrtdBy(String dlrRegCrtdBy);

	/**
	 * Returns the create date of this dgf dlr reg dtls.
	 *
	 * @return the create date of this dgf dlr reg dtls
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dgf dlr reg dtls.
	 *
	 * @param createDate the create date of this dgf dlr reg dtls
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the last updtd by of this dgf dlr reg dtls.
	 *
	 * @return the last updtd by of this dgf dlr reg dtls
	 */
	public long getLastUpdtdBy();

	/**
	 * Sets the last updtd by of this dgf dlr reg dtls.
	 *
	 * @param lastUpdtdBy the last updtd by of this dgf dlr reg dtls
	 */
	public void setLastUpdtdBy(long lastUpdtdBy);

	/**
	 * Returns the modifed date of this dgf dlr reg dtls.
	 *
	 * @return the modifed date of this dgf dlr reg dtls
	 */
	public Date getModifedDate();

	/**
	 * Sets the modifed date of this dgf dlr reg dtls.
	 *
	 * @param modifedDate the modifed date of this dgf dlr reg dtls
	 */
	public void setModifedDate(Date modifedDate);

	/**
	 * Returns the dlr oms sub type of this dgf dlr reg dtls.
	 *
	 * @return the dlr oms sub type of this dgf dlr reg dtls
	 */
	@AutoEscape
	public String getDlrOmsSubType();

	/**
	 * Sets the dlr oms sub type of this dgf dlr reg dtls.
	 *
	 * @param dlrOmsSubType the dlr oms sub type of this dgf dlr reg dtls
	 */
	public void setDlrOmsSubType(String dlrOmsSubType);

	/**
	 * Returns the division of this dgf dlr reg dtls.
	 *
	 * @return the division of this dgf dlr reg dtls
	 */
	public long getDivision();

	/**
	 * Sets the division of this dgf dlr reg dtls.
	 *
	 * @param division the division of this dgf dlr reg dtls
	 */
	public void setDivision(long division);

	/**
	 * Returns the district of this dgf dlr reg dtls.
	 *
	 * @return the district of this dgf dlr reg dtls
	 */
	public long getDistrict();

	/**
	 * Sets the district of this dgf dlr reg dtls.
	 *
	 * @param district the district of this dgf dlr reg dtls
	 */
	public void setDistrict(long district);

	/**
	 * Returns the upzilla of this dgf dlr reg dtls.
	 *
	 * @return the upzilla of this dgf dlr reg dtls
	 */
	public long getUpzilla();

	/**
	 * Sets the upzilla of this dgf dlr reg dtls.
	 *
	 * @param upzilla the upzilla of this dgf dlr reg dtls
	 */
	public void setUpzilla(long upzilla);

	/**
	 * Returns the union name of this dgf dlr reg dtls.
	 *
	 * @return the union name of this dgf dlr reg dtls
	 */
	public long getUnionName();

	/**
	 * Sets the union name of this dgf dlr reg dtls.
	 *
	 * @param unionName the union name of this dgf dlr reg dtls
	 */
	public void setUnionName(long unionName);

	/**
	 * Returns the dlr brth date of this dgf dlr reg dtls.
	 *
	 * @return the dlr brth date of this dgf dlr reg dtls
	 */
	public Date getDlrBrthDate();

	/**
	 * Sets the dlr brth date of this dgf dlr reg dtls.
	 *
	 * @param dlrBrthDate the dlr brth date of this dgf dlr reg dtls
	 */
	public void setDlrBrthDate(Date dlrBrthDate);

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is approved.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is denied.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is a draft.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is expired.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is inactive.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is incomplete.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is pending.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this dgf dlr reg dtls is scheduled.
	 *
	 * @return <code>true</code> if this dgf dlr reg dtls is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public DgfDlrRegDtls cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}