/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model.impl;

import bd.gov.dgfood.food.grain.license.model.dgfLocDivision;
import bd.gov.dgfood.food.grain.license.model.dgfLocDivisionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the dgfLocDivision service. Represents a row in the &quot;dgf_loc_division&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>dgfLocDivisionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dgfLocDivisionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see dgfLocDivisionImpl
 * @generated
 */
@JSON(strict = true)
public class dgfLocDivisionModelImpl
	extends BaseModelImpl<dgfLocDivision> implements dgfLocDivisionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dgf loc division model instance should use the <code>dgfLocDivision</code> interface instead.
	 */
	public static final String TABLE_NAME = "dgf_loc_division";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"name", Types.VARCHAR},
		{"bnName", Types.VARCHAR}, {"url", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"createdAt", Types.TIMESTAMP},
		{"updatedAt", Types.TIMESTAMP}, {"geoCode", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bnName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdAt", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updatedAt", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("geoCode", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dgf_loc_division (id_ LONG not null primary key,name VARCHAR(75) null,bnName VARCHAR(75) null,url VARCHAR(75) null,status VARCHAR(75) null,createdAt DATE null,updatedAt DATE null,geoCode LONG)";

	public static final String TABLE_SQL_DROP = "drop table dgf_loc_division";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dgfLocDivision.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dgf_loc_division.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public dgfLocDivisionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return dgfLocDivision.class;
	}

	@Override
	public String getModelClassName() {
		return dgfLocDivision.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<dgfLocDivision, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<dgfLocDivision, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<dgfLocDivision, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((dgfLocDivision)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<dgfLocDivision, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<dgfLocDivision, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(dgfLocDivision)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<dgfLocDivision, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<dgfLocDivision, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<dgfLocDivision, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<dgfLocDivision, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<dgfLocDivision, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<dgfLocDivision, Object>>();
		Map<String, BiConsumer<dgfLocDivision, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<dgfLocDivision, ?>>();

		attributeGetterFunctions.put("id", dgfLocDivision::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<dgfLocDivision, Long>)dgfLocDivision::setId);
		attributeGetterFunctions.put("name", dgfLocDivision::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<dgfLocDivision, String>)dgfLocDivision::setName);
		attributeGetterFunctions.put("bnName", dgfLocDivision::getBnName);
		attributeSetterBiConsumers.put(
			"bnName",
			(BiConsumer<dgfLocDivision, String>)dgfLocDivision::setBnName);
		attributeGetterFunctions.put("url", dgfLocDivision::getUrl);
		attributeSetterBiConsumers.put(
			"url", (BiConsumer<dgfLocDivision, String>)dgfLocDivision::setUrl);
		attributeGetterFunctions.put("status", dgfLocDivision::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<dgfLocDivision, String>)dgfLocDivision::setStatus);
		attributeGetterFunctions.put("createdAt", dgfLocDivision::getCreatedAt);
		attributeSetterBiConsumers.put(
			"createdAt",
			(BiConsumer<dgfLocDivision, Date>)dgfLocDivision::setCreatedAt);
		attributeGetterFunctions.put("updatedAt", dgfLocDivision::getUpdatedAt);
		attributeSetterBiConsumers.put(
			"updatedAt",
			(BiConsumer<dgfLocDivision, Date>)dgfLocDivision::setUpdatedAt);
		attributeGetterFunctions.put("geoCode", dgfLocDivision::getGeoCode);
		attributeSetterBiConsumers.put(
			"geoCode",
			(BiConsumer<dgfLocDivision, Long>)dgfLocDivision::setGeoCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getBnName() {
		if (_bnName == null) {
			return "";
		}
		else {
			return _bnName;
		}
	}

	@Override
	public void setBnName(String bnName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bnName = bnName;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@JSON
	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	@JSON
	@Override
	public long getGeoCode() {
		return _geoCode;
	}

	@Override
	public void setGeoCode(long geoCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_geoCode = geoCode;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, dgfLocDivision.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public dgfLocDivision toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, dgfLocDivision>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		dgfLocDivisionImpl dgfLocDivisionImpl = new dgfLocDivisionImpl();

		dgfLocDivisionImpl.setId(getId());
		dgfLocDivisionImpl.setName(getName());
		dgfLocDivisionImpl.setBnName(getBnName());
		dgfLocDivisionImpl.setUrl(getUrl());
		dgfLocDivisionImpl.setStatus(getStatus());
		dgfLocDivisionImpl.setCreatedAt(getCreatedAt());
		dgfLocDivisionImpl.setUpdatedAt(getUpdatedAt());
		dgfLocDivisionImpl.setGeoCode(getGeoCode());

		dgfLocDivisionImpl.resetOriginalValues();

		return dgfLocDivisionImpl;
	}

	@Override
	public dgfLocDivision cloneWithOriginalValues() {
		dgfLocDivisionImpl dgfLocDivisionImpl = new dgfLocDivisionImpl();

		dgfLocDivisionImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		dgfLocDivisionImpl.setName(this.<String>getColumnOriginalValue("name"));
		dgfLocDivisionImpl.setBnName(
			this.<String>getColumnOriginalValue("bnName"));
		dgfLocDivisionImpl.setUrl(this.<String>getColumnOriginalValue("url"));
		dgfLocDivisionImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		dgfLocDivisionImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("createdAt"));
		dgfLocDivisionImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updatedAt"));
		dgfLocDivisionImpl.setGeoCode(
			this.<Long>getColumnOriginalValue("geoCode"));

		return dgfLocDivisionImpl;
	}

	@Override
	public int compareTo(dgfLocDivision dgfLocDivision) {
		long primaryKey = dgfLocDivision.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof dgfLocDivision)) {
			return false;
		}

		dgfLocDivision dgfLocDivision = (dgfLocDivision)object;

		long primaryKey = dgfLocDivision.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<dgfLocDivision> toCacheModel() {
		dgfLocDivisionCacheModel dgfLocDivisionCacheModel =
			new dgfLocDivisionCacheModel();

		dgfLocDivisionCacheModel.id = getId();

		dgfLocDivisionCacheModel.name = getName();

		String name = dgfLocDivisionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dgfLocDivisionCacheModel.name = null;
		}

		dgfLocDivisionCacheModel.bnName = getBnName();

		String bnName = dgfLocDivisionCacheModel.bnName;

		if ((bnName != null) && (bnName.length() == 0)) {
			dgfLocDivisionCacheModel.bnName = null;
		}

		dgfLocDivisionCacheModel.url = getUrl();

		String url = dgfLocDivisionCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			dgfLocDivisionCacheModel.url = null;
		}

		dgfLocDivisionCacheModel.status = getStatus();

		String status = dgfLocDivisionCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			dgfLocDivisionCacheModel.status = null;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			dgfLocDivisionCacheModel.createdAt = createdAt.getTime();
		}
		else {
			dgfLocDivisionCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			dgfLocDivisionCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			dgfLocDivisionCacheModel.updatedAt = Long.MIN_VALUE;
		}

		dgfLocDivisionCacheModel.geoCode = getGeoCode();

		return dgfLocDivisionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<dgfLocDivision, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<dgfLocDivision, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<dgfLocDivision, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((dgfLocDivision)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, dgfLocDivision>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					dgfLocDivision.class, ModelWrapper.class);

	}

	private long _id;
	private String _name;
	private String _bnName;
	private String _url;
	private String _status;
	private Date _createdAt;
	private Date _updatedAt;
	private long _geoCode;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<dgfLocDivision, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((dgfLocDivision)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("bnName", _bnName);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("createdAt", _createdAt);
		_columnOriginalValues.put("updatedAt", _updatedAt);
		_columnOriginalValues.put("geoCode", _geoCode);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("bnName", 4L);

		columnBitmasks.put("url", 8L);

		columnBitmasks.put("status", 16L);

		columnBitmasks.put("createdAt", 32L);

		columnBitmasks.put("updatedAt", 64L);

		columnBitmasks.put("geoCode", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private dgfLocDivision _escapedModel;

}