/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfDistributionSchedules service. Represents a row in the &quot;dgf_distribution_schedules&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.DgfDistributionSchedulesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.DgfDistributionSchedulesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfDistributionSchedules
 * @generated
 */
@ProviderType
public interface DgfDistributionSchedulesModel
	extends BaseModel<DgfDistributionSchedules> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf distribution schedules model instance should use the {@link DgfDistributionSchedules} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf distribution schedules.
	 *
	 * @return the primary key of this dgf distribution schedules
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this dgf distribution schedules.
	 *
	 * @param primaryKey the primary key of this dgf distribution schedules
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this dgf distribution schedules.
	 *
	 * @return the ID of this dgf distribution schedules
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this dgf distribution schedules.
	 *
	 * @param id the ID of this dgf distribution schedules
	 */
	public void setId(String id);

	/**
	 * Returns the distribution year of this dgf distribution schedules.
	 *
	 * @return the distribution year of this dgf distribution schedules
	 */
	public long getDistributionYear();

	/**
	 * Sets the distribution year of this dgf distribution schedules.
	 *
	 * @param distributionYear the distribution year of this dgf distribution schedules
	 */
	public void setDistributionYear(long distributionYear);

	/**
	 * Returns the distribution month of this dgf distribution schedules.
	 *
	 * @return the distribution month of this dgf distribution schedules
	 */
	@AutoEscape
	public String getDistributionMonth();

	/**
	 * Sets the distribution month of this dgf distribution schedules.
	 *
	 * @param distributionMonth the distribution month of this dgf distribution schedules
	 */
	public void setDistributionMonth(String distributionMonth);

	/**
	 * Returns the open status of this dgf distribution schedules.
	 *
	 * @return the open status of this dgf distribution schedules
	 */
	@AutoEscape
	public String getOpenStatus();

	/**
	 * Sets the open status of this dgf distribution schedules.
	 *
	 * @param openStatus the open status of this dgf distribution schedules
	 */
	public void setOpenStatus(String openStatus);

	/**
	 * Returns the start date of this dgf distribution schedules.
	 *
	 * @return the start date of this dgf distribution schedules
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this dgf distribution schedules.
	 *
	 * @param startDate the start date of this dgf distribution schedules
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this dgf distribution schedules.
	 *
	 * @return the end date of this dgf distribution schedules
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this dgf distribution schedules.
	 *
	 * @param endDate the end date of this dgf distribution schedules
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the remarks of this dgf distribution schedules.
	 *
	 * @return the remarks of this dgf distribution schedules
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this dgf distribution schedules.
	 *
	 * @param remarks the remarks of this dgf distribution schedules
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the user ID of this dgf distribution schedules.
	 *
	 * @return the user ID of this dgf distribution schedules
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dgf distribution schedules.
	 *
	 * @param userId the user ID of this dgf distribution schedules
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dgf distribution schedules.
	 *
	 * @return the user uuid of this dgf distribution schedules
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dgf distribution schedules.
	 *
	 * @param userUuid the user uuid of this dgf distribution schedules
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created at of this dgf distribution schedules.
	 *
	 * @return the created at of this dgf distribution schedules
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this dgf distribution schedules.
	 *
	 * @param createdAt the created at of this dgf distribution schedules
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this dgf distribution schedules.
	 *
	 * @return the updated at of this dgf distribution schedules
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this dgf distribution schedules.
	 *
	 * @param updatedAt the updated at of this dgf distribution schedules
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public DgfDistributionSchedules cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}