/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfFglLicenseNo service. Represents a row in the &quot;dgf_fgl_license_no&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.DgfFglLicenseNoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.DgfFglLicenseNoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfFglLicenseNo
 * @generated
 */
@ProviderType
public interface DgfFglLicenseNoModel extends BaseModel<DgfFglLicenseNo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf fgl license no model instance should use the {@link DgfFglLicenseNo} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf fgl license no.
	 *
	 * @return the primary key of this dgf fgl license no
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf fgl license no.
	 *
	 * @param primaryKey the primary key of this dgf fgl license no
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dgf fgl license no.
	 *
	 * @return the ID of this dgf fgl license no
	 */
	public long getId();

	/**
	 * Sets the ID of this dgf fgl license no.
	 *
	 * @param id the ID of this dgf fgl license no
	 */
	public void setId(long id);

	/**
	 * Returns the suffix of this dgf fgl license no.
	 *
	 * @return the suffix of this dgf fgl license no
	 */
	public long getSuffix();

	/**
	 * Sets the suffix of this dgf fgl license no.
	 *
	 * @param suffix the suffix of this dgf fgl license no
	 */
	public void setSuffix(long suffix);

	/**
	 * Returns the prefix of this dgf fgl license no.
	 *
	 * @return the prefix of this dgf fgl license no
	 */
	public long getPrefix();

	/**
	 * Sets the prefix of this dgf fgl license no.
	 *
	 * @param prefix the prefix of this dgf fgl license no
	 */
	public void setPrefix(long prefix);

	/**
	 * Returns the serial no of this dgf fgl license no.
	 *
	 * @return the serial no of this dgf fgl license no
	 */
	public long getSerialNo();

	/**
	 * Sets the serial no of this dgf fgl license no.
	 *
	 * @param serialNo the serial no of this dgf fgl license no
	 */
	public void setSerialNo(long serialNo);

	/**
	 * Returns the license no of this dgf fgl license no.
	 *
	 * @return the license no of this dgf fgl license no
	 */
	@AutoEscape
	public String getLicenseNo();

	/**
	 * Sets the license no of this dgf fgl license no.
	 *
	 * @param licenseNo the license no of this dgf fgl license no
	 */
	public void setLicenseNo(String licenseNo);

	/**
	 * Returns the created at of this dgf fgl license no.
	 *
	 * @return the created at of this dgf fgl license no
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this dgf fgl license no.
	 *
	 * @param createdAt the created at of this dgf fgl license no
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this dgf fgl license no.
	 *
	 * @return the updated at of this dgf fgl license no
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this dgf fgl license no.
	 *
	 * @param updatedAt the updated at of this dgf fgl license no
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public DgfFglLicenseNo cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}