/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfUsersForthnightReportC service. Represents a row in the &quot;dgf_users_fortnight_report_c&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersForthnightReportCModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersForthnightReportCImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfUsersForthnightReportC
 * @generated
 */
@ProviderType
public interface DgfUsersForthnightReportCModel
	extends BaseModel<DgfUsersForthnightReportC> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf users forthnight report c model instance should use the {@link DgfUsersForthnightReportC} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf users forthnight report c.
	 *
	 * @return the primary key of this dgf users forthnight report c
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf users forthnight report c.
	 *
	 * @param primaryKey the primary key of this dgf users forthnight report c
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the report ID of this dgf users forthnight report c.
	 *
	 * @return the report ID of this dgf users forthnight report c
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this dgf users forthnight report c.
	 *
	 * @param reportId the report ID of this dgf users forthnight report c
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the user ID of this dgf users forthnight report c.
	 *
	 * @return the user ID of this dgf users forthnight report c
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dgf users forthnight report c.
	 *
	 * @param userId the user ID of this dgf users forthnight report c
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dgf users forthnight report c.
	 *
	 * @return the user uuid of this dgf users forthnight report c
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dgf users forthnight report c.
	 *
	 * @param userUuid the user uuid of this dgf users forthnight report c
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the usernational ID of this dgf users forthnight report c.
	 *
	 * @return the usernational ID of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getUsernationalId();

	/**
	 * Sets the usernational ID of this dgf users forthnight report c.
	 *
	 * @param usernationalId the usernational ID of this dgf users forthnight report c
	 */
	public void setUsernationalId(String usernationalId);

	/**
	 * Returns the screen name of this dgf users forthnight report c.
	 *
	 * @return the screen name of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this dgf users forthnight report c.
	 *
	 * @param screenName the screen name of this dgf users forthnight report c
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the full name of this dgf users forthnight report c.
	 *
	 * @return the full name of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this dgf users forthnight report c.
	 *
	 * @param fullName the full name of this dgf users forthnight report c
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the product type of this dgf users forthnight report c.
	 *
	 * @return the product type of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getProductType();

	/**
	 * Sets the product type of this dgf users forthnight report c.
	 *
	 * @param productType the product type of this dgf users forthnight report c
	 */
	public void setProductType(String productType);

	/**
	 * Returns the start date of this dgf users forthnight report c.
	 *
	 * @return the start date of this dgf users forthnight report c
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this dgf users forthnight report c.
	 *
	 * @param startDate the start date of this dgf users forthnight report c
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this dgf users forthnight report c.
	 *
	 * @return the end date of this dgf users forthnight report c
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this dgf users forthnight report c.
	 *
	 * @param endDate the end date of this dgf users forthnight report c
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the product of this dgf users forthnight report c.
	 *
	 * @return the product of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this dgf users forthnight report c.
	 *
	 * @param product the product of this dgf users forthnight report c
	 */
	public void setProduct(String product);

	/**
	 * Returns the daterecipt of this dgf users forthnight report c.
	 *
	 * @return the daterecipt of this dgf users forthnight report c
	 */
	public Date getDaterecipt();

	/**
	 * Sets the daterecipt of this dgf users forthnight report c.
	 *
	 * @param daterecipt the daterecipt of this dgf users forthnight report c
	 */
	public void setDaterecipt(Date daterecipt);

	/**
	 * Returns the received quantity of this dgf users forthnight report c.
	 *
	 * @return the received quantity of this dgf users forthnight report c
	 */
	public int getReceivedQuantity();

	/**
	 * Sets the received quantity of this dgf users forthnight report c.
	 *
	 * @param receivedQuantity the received quantity of this dgf users forthnight report c
	 */
	public void setReceivedQuantity(int receivedQuantity);

	/**
	 * Returns the received quantity unit of this dgf users forthnight report c.
	 *
	 * @return the received quantity unit of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getReceivedQuantityUnit();

	/**
	 * Sets the received quantity unit of this dgf users forthnight report c.
	 *
	 * @param receivedQuantityUnit the received quantity unit of this dgf users forthnight report c
	 */
	public void setReceivedQuantityUnit(String receivedQuantityUnit);

	/**
	 * Returns the last date approve of this dgf users forthnight report c.
	 *
	 * @return the last date approve of this dgf users forthnight report c
	 */
	public Date getLastDateApprove();

	/**
	 * Sets the last date approve of this dgf users forthnight report c.
	 *
	 * @param lastDateApprove the last date approve of this dgf users forthnight report c
	 */
	public void setLastDateApprove(Date lastDateApprove);

	/**
	 * Returns the unsold quantity of this dgf users forthnight report c.
	 *
	 * @return the unsold quantity of this dgf users forthnight report c
	 */
	public int getUnsoldQuantity();

	/**
	 * Sets the unsold quantity of this dgf users forthnight report c.
	 *
	 * @param unsoldQuantity the unsold quantity of this dgf users forthnight report c
	 */
	public void setUnsoldQuantity(int unsoldQuantity);

	/**
	 * Returns the unsolddunit of this dgf users forthnight report c.
	 *
	 * @return the unsolddunit of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getUnsolddunit();

	/**
	 * Sets the unsolddunit of this dgf users forthnight report c.
	 *
	 * @param unsolddunit the unsolddunit of this dgf users forthnight report c
	 */
	public void setUnsolddunit(String unsolddunit);

	/**
	 * Returns the reason for being unsold of this dgf users forthnight report c.
	 *
	 * @return the reason for being unsold of this dgf users forthnight report c
	 */
	@AutoEscape
	public String getReasonForBeingUnsold();

	/**
	 * Sets the reason for being unsold of this dgf users forthnight report c.
	 *
	 * @param reasonForBeingUnsold the reason for being unsold of this dgf users forthnight report c
	 */
	public void setReasonForBeingUnsold(String reasonForBeingUnsold);

	@Override
	public DgfUsersForthnightReportC cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}