/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfUsersFortnightReportDForm service. Represents a row in the &quot;dgf_users_fortnightreport_d&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersFortnightReportDFormModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersFortnightReportDFormImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfUsersFortnightReportDForm
 * @generated
 */
@ProviderType
public interface DgfUsersFortnightReportDFormModel
	extends BaseModel<DgfUsersFortnightReportDForm> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf users fortnight report d form model instance should use the {@link DgfUsersFortnightReportDForm} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf users fortnight report d form.
	 *
	 * @return the primary key of this dgf users fortnight report d form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf users fortnight report d form.
	 *
	 * @param primaryKey the primary key of this dgf users fortnight report d form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the report ID of this dgf users fortnight report d form.
	 *
	 * @return the report ID of this dgf users fortnight report d form
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this dgf users fortnight report d form.
	 *
	 * @param reportId the report ID of this dgf users fortnight report d form
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the user ID of this dgf users fortnight report d form.
	 *
	 * @return the user ID of this dgf users fortnight report d form
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dgf users fortnight report d form.
	 *
	 * @param userId the user ID of this dgf users fortnight report d form
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dgf users fortnight report d form.
	 *
	 * @return the user uuid of this dgf users fortnight report d form
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dgf users fortnight report d form.
	 *
	 * @param userUuid the user uuid of this dgf users fortnight report d form
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the usernational ID of this dgf users fortnight report d form.
	 *
	 * @return the usernational ID of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getUsernationalId();

	/**
	 * Sets the usernational ID of this dgf users fortnight report d form.
	 *
	 * @param usernationalId the usernational ID of this dgf users fortnight report d form
	 */
	public void setUsernationalId(String usernationalId);

	/**
	 * Returns the license no of this dgf users fortnight report d form.
	 *
	 * @return the license no of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getLicenseNo();

	/**
	 * Sets the license no of this dgf users fortnight report d form.
	 *
	 * @param licenseNo the license no of this dgf users fortnight report d form
	 */
	public void setLicenseNo(String licenseNo);

	/**
	 * Returns the screen name of this dgf users fortnight report d form.
	 *
	 * @return the screen name of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this dgf users fortnight report d form.
	 *
	 * @param screenName the screen name of this dgf users fortnight report d form
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the full name of this dgf users fortnight report d form.
	 *
	 * @return the full name of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this dgf users fortnight report d form.
	 *
	 * @param fullName the full name of this dgf users fortnight report d form
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the bussiness type of this dgf users fortnight report d form.
	 *
	 * @return the bussiness type of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getBussinessType();

	/**
	 * Sets the bussiness type of this dgf users fortnight report d form.
	 *
	 * @param bussinessType the bussiness type of this dgf users fortnight report d form
	 */
	public void setBussinessType(String bussinessType);

	/**
	 * Returns the start date of this dgf users fortnight report d form.
	 *
	 * @return the start date of this dgf users fortnight report d form
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this dgf users fortnight report d form.
	 *
	 * @param startDate the start date of this dgf users fortnight report d form
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this dgf users fortnight report d form.
	 *
	 * @return the end date of this dgf users fortnight report d form
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this dgf users fortnight report d form.
	 *
	 * @param endDate the end date of this dgf users fortnight report d form
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the product of this dgf users fortnight report d form.
	 *
	 * @return the product of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this dgf users fortnight report d form.
	 *
	 * @param product the product of this dgf users fortnight report d form
	 */
	public void setProduct(String product);

	/**
	 * Returns the inital stock on of this dgf users fortnight report d form.
	 *
	 * @return the inital stock on of this dgf users fortnight report d form
	 */
	public int getInitalStockOn();

	/**
	 * Sets the inital stock on of this dgf users fortnight report d form.
	 *
	 * @param initalStockOn the inital stock on of this dgf users fortnight report d form
	 */
	public void setInitalStockOn(int initalStockOn);

	/**
	 * Returns the inital stock on unit of this dgf users fortnight report d form.
	 *
	 * @return the inital stock on unit of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getInitalStockOnUnit();

	/**
	 * Sets the inital stock on unit of this dgf users fortnight report d form.
	 *
	 * @param initalStockOnUnit the inital stock on unit of this dgf users fortnight report d form
	 */
	public void setInitalStockOnUnit(String initalStockOnUnit);

	/**
	 * Returns the recived quantity of this dgf users fortnight report d form.
	 *
	 * @return the recived quantity of this dgf users fortnight report d form
	 */
	public int getRecivedQuantity();

	/**
	 * Sets the recived quantity of this dgf users fortnight report d form.
	 *
	 * @param recivedQuantity the recived quantity of this dgf users fortnight report d form
	 */
	public void setRecivedQuantity(int recivedQuantity);

	/**
	 * Returns the recived quantity unit of this dgf users fortnight report d form.
	 *
	 * @return the recived quantity unit of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getRecivedQuantityUnit();

	/**
	 * Sets the recived quantity unit of this dgf users fortnight report d form.
	 *
	 * @param recivedQuantityUnit the recived quantity unit of this dgf users fortnight report d form
	 */
	public void setRecivedQuantityUnit(String recivedQuantityUnit);

	/**
	 * Returns the selling quantity of this dgf users fortnight report d form.
	 *
	 * @return the selling quantity of this dgf users fortnight report d form
	 */
	public int getSellingQuantity();

	/**
	 * Sets the selling quantity of this dgf users fortnight report d form.
	 *
	 * @param sellingQuantity the selling quantity of this dgf users fortnight report d form
	 */
	public void setSellingQuantity(int sellingQuantity);

	/**
	 * Returns the selling quantity unit of this dgf users fortnight report d form.
	 *
	 * @return the selling quantity unit of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getSellingQuantityUnit();

	/**
	 * Sets the selling quantity unit of this dgf users fortnight report d form.
	 *
	 * @param sellingQuantityUnit the selling quantity unit of this dgf users fortnight report d form
	 */
	public void setSellingQuantityUnit(String sellingQuantityUnit);

	/**
	 * Returns the quantity of finishing stock of this dgf users fortnight report d form.
	 *
	 * @return the quantity of finishing stock of this dgf users fortnight report d form
	 */
	public int getQuantityOfFinishingStock();

	/**
	 * Sets the quantity of finishing stock of this dgf users fortnight report d form.
	 *
	 * @param quantityOfFinishingStock the quantity of finishing stock of this dgf users fortnight report d form
	 */
	public void setQuantityOfFinishingStock(int quantityOfFinishingStock);

	/**
	 * Returns the quantity of finishing stock unit of this dgf users fortnight report d form.
	 *
	 * @return the quantity of finishing stock unit of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getQuantityOfFinishingStockUnit();

	/**
	 * Sets the quantity of finishing stock unit of this dgf users fortnight report d form.
	 *
	 * @param quantityOfFinishingStockUnit the quantity of finishing stock unit of this dgf users fortnight report d form
	 */
	public void setQuantityOfFinishingStockUnit(
		String quantityOfFinishingStockUnit);

	/**
	 * Returns the comment of this dgf users fortnight report d form.
	 *
	 * @return the comment of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this dgf users fortnight report d form.
	 *
	 * @param comment the comment of this dgf users fortnight report d form
	 */
	public void setComment(String comment);

	/**
	 * Returns the national ID of this dgf users fortnight report d form.
	 *
	 * @return the national ID of this dgf users fortnight report d form
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this dgf users fortnight report d form.
	 *
	 * @param nationalId the national ID of this dgf users fortnight report d form
	 */
	public void setNationalId(String nationalId);

	@Override
	public DgfUsersFortnightReportDForm cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}