/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DgfUsersDtls service. Represents a row in the &quot;dgf_users_dtls&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersDtlsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.DgfUsersDtlsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DgfUsersDtls
 * @generated
 */
@ProviderType
public interface DgfUsersDtlsModel extends BaseModel<DgfUsersDtls> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dgf users dtls model instance should use the {@link DgfUsersDtls} interface instead.
	 */

	/**
	 * Returns the primary key of this dgf users dtls.
	 *
	 * @return the primary key of this dgf users dtls
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dgf users dtls.
	 *
	 * @param primaryKey the primary key of this dgf users dtls
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user details ID of this dgf users dtls.
	 *
	 * @return the user details ID of this dgf users dtls
	 */
	public long getUserDetailsId();

	/**
	 * Sets the user details ID of this dgf users dtls.
	 *
	 * @param userDetailsId the user details ID of this dgf users dtls
	 */
	public void setUserDetailsId(long userDetailsId);

	/**
	 * Returns the national ID of this dgf users dtls.
	 *
	 * @return the national ID of this dgf users dtls
	 */
	public long getNationalId();

	/**
	 * Sets the national ID of this dgf users dtls.
	 *
	 * @param nationalId the national ID of this dgf users dtls
	 */
	public void setNationalId(long nationalId);

	/**
	 * Returns the email of this dgf users dtls.
	 *
	 * @return the email of this dgf users dtls
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this dgf users dtls.
	 *
	 * @param email the email of this dgf users dtls
	 */
	public void setEmail(String email);

	/**
	 * Returns the nid photo attch ID of this dgf users dtls.
	 *
	 * @return the nid photo attch ID of this dgf users dtls
	 */
	public long getNidPhotoAttchId();

	/**
	 * Sets the nid photo attch ID of this dgf users dtls.
	 *
	 * @param nidPhotoAttchId the nid photo attch ID of this dgf users dtls
	 */
	public void setNidPhotoAttchId(long nidPhotoAttchId);

	/**
	 * Returns the nid division of this dgf users dtls.
	 *
	 * @return the nid division of this dgf users dtls
	 */
	@AutoEscape
	public String getNidDivision();

	/**
	 * Sets the nid division of this dgf users dtls.
	 *
	 * @param nidDivision the nid division of this dgf users dtls
	 */
	public void setNidDivision(String nidDivision);

	/**
	 * Returns the nid district of this dgf users dtls.
	 *
	 * @return the nid district of this dgf users dtls
	 */
	@AutoEscape
	public String getNidDistrict();

	/**
	 * Sets the nid district of this dgf users dtls.
	 *
	 * @param nidDistrict the nid district of this dgf users dtls
	 */
	public void setNidDistrict(String nidDistrict);

	/**
	 * Returns the nid upzilla of this dgf users dtls.
	 *
	 * @return the nid upzilla of this dgf users dtls
	 */
	@AutoEscape
	public String getNidUpzilla();

	/**
	 * Sets the nid upzilla of this dgf users dtls.
	 *
	 * @param nidUpzilla the nid upzilla of this dgf users dtls
	 */
	public void setNidUpzilla(String nidUpzilla);

	/**
	 * Returns the nid union of this dgf users dtls.
	 *
	 * @return the nid union of this dgf users dtls
	 */
	@AutoEscape
	public String getNidUnion();

	/**
	 * Sets the nid union of this dgf users dtls.
	 *
	 * @param nidUnion the nid union of this dgf users dtls
	 */
	public void setNidUnion(String nidUnion);

	/**
	 * Returns the nid village of this dgf users dtls.
	 *
	 * @return the nid village of this dgf users dtls
	 */
	@AutoEscape
	public String getNidVillage();

	/**
	 * Sets the nid village of this dgf users dtls.
	 *
	 * @param nidVillage the nid village of this dgf users dtls
	 */
	public void setNidVillage(String nidVillage);

	/**
	 * Returns the nid ward of this dgf users dtls.
	 *
	 * @return the nid ward of this dgf users dtls
	 */
	@AutoEscape
	public String getNidWard();

	/**
	 * Sets the nid ward of this dgf users dtls.
	 *
	 * @param nidWard the nid ward of this dgf users dtls
	 */
	public void setNidWard(String nidWard);

	/**
	 * Returns the nid zip code of this dgf users dtls.
	 *
	 * @return the nid zip code of this dgf users dtls
	 */
	@AutoEscape
	public String getNidZipCode();

	/**
	 * Sets the nid zip code of this dgf users dtls.
	 *
	 * @param nidZipCode the nid zip code of this dgf users dtls
	 */
	public void setNidZipCode(String nidZipCode);

	/**
	 * Returns the nid house address of this dgf users dtls.
	 *
	 * @return the nid house address of this dgf users dtls
	 */
	@AutoEscape
	public String getNidHouseAddress();

	/**
	 * Sets the nid house address of this dgf users dtls.
	 *
	 * @param nidHouseAddress the nid house address of this dgf users dtls
	 */
	public void setNidHouseAddress(String nidHouseAddress);

	/**
	 * Returns the last updated date of this dgf users dtls.
	 *
	 * @return the last updated date of this dgf users dtls
	 */
	public Date getLastUpdatedDate();

	/**
	 * Sets the last updated date of this dgf users dtls.
	 *
	 * @param lastUpdatedDate the last updated date of this dgf users dtls
	 */
	public void setLastUpdatedDate(Date lastUpdatedDate);

	/**
	 * Returns the nid post office of this dgf users dtls.
	 *
	 * @return the nid post office of this dgf users dtls
	 */
	@AutoEscape
	public String getNidPostOffice();

	/**
	 * Sets the nid post office of this dgf users dtls.
	 *
	 * @param nidPostOffice the nid post office of this dgf users dtls
	 */
	public void setNidPostOffice(String nidPostOffice);

	@Override
	public DgfUsersDtls cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}