/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.grain.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the licnsUserRegs service. Represents a row in the &quot;dgf_licns_user_regs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.grain.license.model.impl.licnsUserRegsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.grain.license.model.impl.licnsUserRegsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see licnsUserRegs
 * @generated
 */
@ProviderType
public interface licnsUserRegsModel extends BaseModel<licnsUserRegs> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a licns user regs model instance should use the {@link licnsUserRegs} interface instead.
	 */

	/**
	 * Returns the primary key of this licns user regs.
	 *
	 * @return the primary key of this licns user regs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this licns user regs.
	 *
	 * @param primaryKey the primary key of this licns user regs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lic user ID of this licns user regs.
	 *
	 * @return the lic user ID of this licns user regs
	 */
	public long getLicUserId();

	/**
	 * Sets the lic user ID of this licns user regs.
	 *
	 * @param licUserId the lic user ID of this licns user regs
	 */
	public void setLicUserId(long licUserId);

	/**
	 * Returns the lic user uuid of this licns user regs.
	 *
	 * @return the lic user uuid of this licns user regs
	 */
	public String getLicUserUuid();

	/**
	 * Sets the lic user uuid of this licns user regs.
	 *
	 * @param licUserUuid the lic user uuid of this licns user regs
	 */
	public void setLicUserUuid(String licUserUuid);

	/**
	 * Returns the national ID of this licns user regs.
	 *
	 * @return the national ID of this licns user regs
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this licns user regs.
	 *
	 * @param nationalId the national ID of this licns user regs
	 */
	public void setNationalId(String nationalId);

	/**
	 * Returns the applicant name of this licns user regs.
	 *
	 * @return the applicant name of this licns user regs
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this licns user regs.
	 *
	 * @param applicantName the applicant name of this licns user regs
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the trade license no of this licns user regs.
	 *
	 * @return the trade license no of this licns user regs
	 */
	@AutoEscape
	public String getTradeLicenseNo();

	/**
	 * Sets the trade license no of this licns user regs.
	 *
	 * @param tradeLicenseNo the trade license no of this licns user regs
	 */
	public void setTradeLicenseNo(String tradeLicenseNo);

	/**
	 * Returns the trade license expiry date of this licns user regs.
	 *
	 * @return the trade license expiry date of this licns user regs
	 */
	public Date getTradeLicenseExpiryDate();

	/**
	 * Sets the trade license expiry date of this licns user regs.
	 *
	 * @param tradeLicenseExpiryDate the trade license expiry date of this licns user regs
	 */
	public void setTradeLicenseExpiryDate(Date tradeLicenseExpiryDate);

	/**
	 * Returns the trade license issuer code of this licns user regs.
	 *
	 * @return the trade license issuer code of this licns user regs
	 */
	@AutoEscape
	public String getTradeLicenseIssuerCode();

	/**
	 * Sets the trade license issuer code of this licns user regs.
	 *
	 * @param tradeLicenseIssuerCode the trade license issuer code of this licns user regs
	 */
	public void setTradeLicenseIssuerCode(String tradeLicenseIssuerCode);

	/**
	 * Returns the trade license issuer city of this licns user regs.
	 *
	 * @return the trade license issuer city of this licns user regs
	 */
	@AutoEscape
	public String getTradeLicenseIssuerCity();

	/**
	 * Sets the trade license issuer city of this licns user regs.
	 *
	 * @param tradeLicenseIssuerCity the trade license issuer city of this licns user regs
	 */
	public void setTradeLicenseIssuerCity(String tradeLicenseIssuerCity);

	/**
	 * Returns the business identification no of this licns user regs.
	 *
	 * @return the business identification no of this licns user regs
	 */
	@AutoEscape
	public String getBusinessIdentificationNo();

	/**
	 * Sets the business identification no of this licns user regs.
	 *
	 * @param businessIdentificationNo the business identification no of this licns user regs
	 */
	public void setBusinessIdentificationNo(String businessIdentificationNo);

	/**
	 * Returns the tax identification no of this licns user regs.
	 *
	 * @return the tax identification no of this licns user regs
	 */
	@AutoEscape
	public String getTaxIdentificationNo();

	/**
	 * Sets the tax identification no of this licns user regs.
	 *
	 * @param taxIdentificationNo the tax identification no of this licns user regs
	 */
	public void setTaxIdentificationNo(String taxIdentificationNo);

	/**
	 * Returns the business name of this licns user regs.
	 *
	 * @return the business name of this licns user regs
	 */
	@AutoEscape
	public String getBusinessName();

	/**
	 * Sets the business name of this licns user regs.
	 *
	 * @param businessName the business name of this licns user regs
	 */
	public void setBusinessName(String businessName);

	/**
	 * Returns the business type of this licns user regs.
	 *
	 * @return the business type of this licns user regs
	 */
	@AutoEscape
	public String getBusinessType();

	/**
	 * Sets the business type of this licns user regs.
	 *
	 * @param businessType the business type of this licns user regs
	 */
	public void setBusinessType(String businessType);

	/**
	 * Returns the business division of this licns user regs.
	 *
	 * @return the business division of this licns user regs
	 */
	public long getBusinessDivision();

	/**
	 * Sets the business division of this licns user regs.
	 *
	 * @param businessDivision the business division of this licns user regs
	 */
	public void setBusinessDivision(long businessDivision);

	/**
	 * Returns the business district of this licns user regs.
	 *
	 * @return the business district of this licns user regs
	 */
	public long getBusinessDistrict();

	/**
	 * Sets the business district of this licns user regs.
	 *
	 * @param businessDistrict the business district of this licns user regs
	 */
	public void setBusinessDistrict(long businessDistrict);

	/**
	 * Returns the business upzilla of this licns user regs.
	 *
	 * @return the business upzilla of this licns user regs
	 */
	public long getBusinessUpzilla();

	/**
	 * Sets the business upzilla of this licns user regs.
	 *
	 * @param businessUpzilla the business upzilla of this licns user regs
	 */
	public void setBusinessUpzilla(long businessUpzilla);

	/**
	 * Returns the business union name of this licns user regs.
	 *
	 * @return the business union name of this licns user regs
	 */
	public long getBusinessUnionName();

	/**
	 * Sets the business union name of this licns user regs.
	 *
	 * @param businessUnionName the business union name of this licns user regs
	 */
	public void setBusinessUnionName(long businessUnionName);

	/**
	 * Returns the business village of this licns user regs.
	 *
	 * @return the business village of this licns user regs
	 */
	@AutoEscape
	public String getBusinessVillage();

	/**
	 * Sets the business village of this licns user regs.
	 *
	 * @param businessVillage the business village of this licns user regs
	 */
	public void setBusinessVillage(String businessVillage);

	/**
	 * Returns the business ward of this licns user regs.
	 *
	 * @return the business ward of this licns user regs
	 */
	@AutoEscape
	public String getBusinessWard();

	/**
	 * Sets the business ward of this licns user regs.
	 *
	 * @param businessWard the business ward of this licns user regs
	 */
	public void setBusinessWard(String businessWard);

	/**
	 * Returns the business zip code of this licns user regs.
	 *
	 * @return the business zip code of this licns user regs
	 */
	@AutoEscape
	public String getBusinessZipCode();

	/**
	 * Sets the business zip code of this licns user regs.
	 *
	 * @param businessZipCode the business zip code of this licns user regs
	 */
	public void setBusinessZipCode(String businessZipCode);

	/**
	 * Returns the business post office of this licns user regs.
	 *
	 * @return the business post office of this licns user regs
	 */
	@AutoEscape
	public String getBusinessPostOffice();

	/**
	 * Sets the business post office of this licns user regs.
	 *
	 * @param businessPostOffice the business post office of this licns user regs
	 */
	public void setBusinessPostOffice(String businessPostOffice);

	/**
	 * Returns the business house address of this licns user regs.
	 *
	 * @return the business house address of this licns user regs
	 */
	@AutoEscape
	public String getBusinessHouseAddress();

	/**
	 * Sets the business house address of this licns user regs.
	 *
	 * @param businessHouseAddress the business house address of this licns user regs
	 */
	public void setBusinessHouseAddress(String businessHouseAddress);

	/**
	 * Returns the photograph file of this licns user regs.
	 *
	 * @return the photograph file of this licns user regs
	 */
	@AutoEscape
	public String getPhotographFile();

	/**
	 * Sets the photograph file of this licns user regs.
	 *
	 * @param photographFile the photograph file of this licns user regs
	 */
	public void setPhotographFile(String photographFile);

	/**
	 * Returns the trade lic doc of this licns user regs.
	 *
	 * @return the trade lic doc of this licns user regs
	 */
	@AutoEscape
	public String getTradeLicDoc();

	/**
	 * Sets the trade lic doc of this licns user regs.
	 *
	 * @param tradeLicDoc the trade lic doc of this licns user regs
	 */
	public void setTradeLicDoc(String tradeLicDoc);

	/**
	 * Returns the bin doc of this licns user regs.
	 *
	 * @return the bin doc of this licns user regs
	 */
	@AutoEscape
	public String getBinDoc();

	/**
	 * Sets the bin doc of this licns user regs.
	 *
	 * @param binDoc the bin doc of this licns user regs
	 */
	public void setBinDoc(String binDoc);

	/**
	 * Returns the tin doc of this licns user regs.
	 *
	 * @return the tin doc of this licns user regs
	 */
	@AutoEscape
	public String getTinDoc();

	/**
	 * Sets the tin doc of this licns user regs.
	 *
	 * @param tinDoc the tin doc of this licns user regs
	 */
	public void setTinDoc(String tinDoc);

	/**
	 * Returns the bank stat of this licns user regs.
	 *
	 * @return the bank stat of this licns user regs
	 */
	@AutoEscape
	public String getBankStat();

	/**
	 * Sets the bank stat of this licns user regs.
	 *
	 * @param bankStat the bank stat of this licns user regs
	 */
	public void setBankStat(String bankStat);

	/**
	 * Returns the other relevent doc of this licns user regs.
	 *
	 * @return the other relevent doc of this licns user regs
	 */
	@AutoEscape
	public String getOtherReleventDoc();

	/**
	 * Sets the other relevent doc of this licns user regs.
	 *
	 * @param otherReleventDoc the other relevent doc of this licns user regs
	 */
	public void setOtherReleventDoc(String otherReleventDoc);

	/**
	 * Returns the comments of this licns user regs.
	 *
	 * @return the comments of this licns user regs
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this licns user regs.
	 *
	 * @param comments the comments of this licns user regs
	 */
	public void setComments(String comments);

	/**
	 * Returns the food grain license type of this licns user regs.
	 *
	 * @return the food grain license type of this licns user regs
	 */
	@AutoEscape
	public String getFoodGrainLicenseType();

	/**
	 * Sets the food grain license type of this licns user regs.
	 *
	 * @param foodGrainLicenseType the food grain license type of this licns user regs
	 */
	public void setFoodGrainLicenseType(String foodGrainLicenseType);

	/**
	 * Returns the division of this licns user regs.
	 *
	 * @return the division of this licns user regs
	 */
	public long getDivision();

	/**
	 * Sets the division of this licns user regs.
	 *
	 * @param division the division of this licns user regs
	 */
	public void setDivision(long division);

	/**
	 * Returns the district of this licns user regs.
	 *
	 * @return the district of this licns user regs
	 */
	public long getDistrict();

	/**
	 * Sets the district of this licns user regs.
	 *
	 * @param district the district of this licns user regs
	 */
	public void setDistrict(long district);

	/**
	 * Returns the upzilla of this licns user regs.
	 *
	 * @return the upzilla of this licns user regs
	 */
	public long getUpzilla();

	/**
	 * Sets the upzilla of this licns user regs.
	 *
	 * @param upzilla the upzilla of this licns user regs
	 */
	public void setUpzilla(long upzilla);

	/**
	 * Returns the union name of this licns user regs.
	 *
	 * @return the union name of this licns user regs
	 */
	public long getUnionName();

	/**
	 * Sets the union name of this licns user regs.
	 *
	 * @param unionName the union name of this licns user regs
	 */
	public void setUnionName(long unionName);

	/**
	 * Returns the village of this licns user regs.
	 *
	 * @return the village of this licns user regs
	 */
	@AutoEscape
	public String getVillage();

	/**
	 * Sets the village of this licns user regs.
	 *
	 * @param village the village of this licns user regs
	 */
	public void setVillage(String village);

	/**
	 * Returns the ward of this licns user regs.
	 *
	 * @return the ward of this licns user regs
	 */
	@AutoEscape
	public String getWard();

	/**
	 * Sets the ward of this licns user regs.
	 *
	 * @param ward the ward of this licns user regs
	 */
	public void setWard(String ward);

	/**
	 * Returns the zip code of this licns user regs.
	 *
	 * @return the zip code of this licns user regs
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this licns user regs.
	 *
	 * @param zipCode the zip code of this licns user regs
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the post office of this licns user regs.
	 *
	 * @return the post office of this licns user regs
	 */
	@AutoEscape
	public String getPostOffice();

	/**
	 * Sets the post office of this licns user regs.
	 *
	 * @param postOffice the post office of this licns user regs
	 */
	public void setPostOffice(String postOffice);

	/**
	 * Returns the house address of this licns user regs.
	 *
	 * @return the house address of this licns user regs
	 */
	@AutoEscape
	public String getHouseAddress();

	/**
	 * Sets the house address of this licns user regs.
	 *
	 * @param houseAddress the house address of this licns user regs
	 */
	public void setHouseAddress(String houseAddress);

	/**
	 * Returns the password of this licns user regs.
	 *
	 * @return the password of this licns user regs
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this licns user regs.
	 *
	 * @param password the password of this licns user regs
	 */
	public void setPassword(String password);

	/**
	 * Returns the father name of this licns user regs.
	 *
	 * @return the father name of this licns user regs
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this licns user regs.
	 *
	 * @param fatherName the father name of this licns user regs
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the last name of this licns user regs.
	 *
	 * @return the last name of this licns user regs
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this licns user regs.
	 *
	 * @param lastName the last name of this licns user regs
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the mother name of this licns user regs.
	 *
	 * @return the mother name of this licns user regs
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this licns user regs.
	 *
	 * @param motherName the mother name of this licns user regs
	 */
	public void setMotherName(String motherName);

	/**
	 * Returns the gender of this licns user regs.
	 *
	 * @return the gender of this licns user regs
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this licns user regs.
	 *
	 * @param gender the gender of this licns user regs
	 */
	public void setGender(String gender);

	/**
	 * Returns the marital status of this licns user regs.
	 *
	 * @return the marital status of this licns user regs
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this licns user regs.
	 *
	 * @param maritalStatus the marital status of this licns user regs
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the birth date of this licns user regs.
	 *
	 * @return the birth date of this licns user regs
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this licns user regs.
	 *
	 * @param birthDate the birth date of this licns user regs
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the mobile no of this licns user regs.
	 *
	 * @return the mobile no of this licns user regs
	 */
	@AutoEscape
	public String getMobileNo();

	/**
	 * Sets the mobile no of this licns user regs.
	 *
	 * @param mobileNo the mobile no of this licns user regs
	 */
	public void setMobileNo(String mobileNo);

	/**
	 * Returns the user ID of this licns user regs.
	 *
	 * @return the user ID of this licns user regs
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this licns user regs.
	 *
	 * @param userId the user ID of this licns user regs
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this licns user regs.
	 *
	 * @return the user uuid of this licns user regs
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this licns user regs.
	 *
	 * @param userUuid the user uuid of this licns user regs
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the email of this licns user regs.
	 *
	 * @return the email of this licns user regs
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this licns user regs.
	 *
	 * @param email the email of this licns user regs
	 */
	public void setEmail(String email);

	/**
	 * Returns the nid division of this licns user regs.
	 *
	 * @return the nid division of this licns user regs
	 */
	@AutoEscape
	public String getNidDivision();

	/**
	 * Sets the nid division of this licns user regs.
	 *
	 * @param nidDivision the nid division of this licns user regs
	 */
	public void setNidDivision(String nidDivision);

	/**
	 * Returns the nid district of this licns user regs.
	 *
	 * @return the nid district of this licns user regs
	 */
	@AutoEscape
	public String getNidDistrict();

	/**
	 * Sets the nid district of this licns user regs.
	 *
	 * @param nidDistrict the nid district of this licns user regs
	 */
	public void setNidDistrict(String nidDistrict);

	/**
	 * Returns the nid upzilla of this licns user regs.
	 *
	 * @return the nid upzilla of this licns user regs
	 */
	@AutoEscape
	public String getNidUpzilla();

	/**
	 * Sets the nid upzilla of this licns user regs.
	 *
	 * @param nidUpzilla the nid upzilla of this licns user regs
	 */
	public void setNidUpzilla(String nidUpzilla);

	/**
	 * Returns the nid union of this licns user regs.
	 *
	 * @return the nid union of this licns user regs
	 */
	@AutoEscape
	public String getNidUnion();

	/**
	 * Sets the nid union of this licns user regs.
	 *
	 * @param nidUnion the nid union of this licns user regs
	 */
	public void setNidUnion(String nidUnion);

	/**
	 * Returns the nid village of this licns user regs.
	 *
	 * @return the nid village of this licns user regs
	 */
	@AutoEscape
	public String getNidVillage();

	/**
	 * Sets the nid village of this licns user regs.
	 *
	 * @param nidVillage the nid village of this licns user regs
	 */
	public void setNidVillage(String nidVillage);

	/**
	 * Returns the nid ward of this licns user regs.
	 *
	 * @return the nid ward of this licns user regs
	 */
	@AutoEscape
	public String getNidWard();

	/**
	 * Sets the nid ward of this licns user regs.
	 *
	 * @param nidWard the nid ward of this licns user regs
	 */
	public void setNidWard(String nidWard);

	/**
	 * Returns the nid zip code of this licns user regs.
	 *
	 * @return the nid zip code of this licns user regs
	 */
	@AutoEscape
	public String getNidZipCode();

	/**
	 * Sets the nid zip code of this licns user regs.
	 *
	 * @param nidZipCode the nid zip code of this licns user regs
	 */
	public void setNidZipCode(String nidZipCode);

	/**
	 * Returns the nid post office of this licns user regs.
	 *
	 * @return the nid post office of this licns user regs
	 */
	@AutoEscape
	public String getNidPostOffice();

	/**
	 * Sets the nid post office of this licns user regs.
	 *
	 * @param nidPostOffice the nid post office of this licns user regs
	 */
	public void setNidPostOffice(String nidPostOffice);

	/**
	 * Returns the nid house address of this licns user regs.
	 *
	 * @return the nid house address of this licns user regs
	 */
	@AutoEscape
	public String getNidHouseAddress();

	/**
	 * Sets the nid house address of this licns user regs.
	 *
	 * @param nidHouseAddress the nid house address of this licns user regs
	 */
	public void setNidHouseAddress(String nidHouseAddress);

	/**
	 * Returns the is submit of this licns user regs.
	 *
	 * @return the is submit of this licns user regs
	 */
	public boolean getIsSubmit();

	/**
	 * Returns <code>true</code> if this licns user regs is is submit.
	 *
	 * @return <code>true</code> if this licns user regs is is submit; <code>false</code> otherwise
	 */
	public boolean isIsSubmit();

	/**
	 * Sets whether this licns user regs is is submit.
	 *
	 * @param isSubmit the is submit of this licns user regs
	 */
	public void setIsSubmit(boolean isSubmit);

	/**
	 * Returns the electric exemption memo of this licns user regs.
	 *
	 * @return the electric exemption memo of this licns user regs
	 */
	@AutoEscape
	public String getElectricExemptionMemo();

	/**
	 * Sets the electric exemption memo of this licns user regs.
	 *
	 * @param electricExemptionMemo the electric exemption memo of this licns user regs
	 */
	public void setElectricExemptionMemo(String electricExemptionMemo);

	/**
	 * Returns the env clr memo of this licns user regs.
	 *
	 * @return the env clr memo of this licns user regs
	 */
	@AutoEscape
	public String getEnvClrMemo();

	/**
	 * Sets the env clr memo of this licns user regs.
	 *
	 * @param envClrMemo the env clr memo of this licns user regs
	 */
	public void setEnvClrMemo(String envClrMemo);

	/**
	 * Returns the bsti clr memo of this licns user regs.
	 *
	 * @return the bsti clr memo of this licns user regs
	 */
	@AutoEscape
	public String getBstiClrMemo();

	/**
	 * Sets the bsti clr memo of this licns user regs.
	 *
	 * @param bstiClrMemo the bsti clr memo of this licns user regs
	 */
	public void setBstiClrMemo(String bstiClrMemo);

	/**
	 * Returns the fire lic num doc of this licns user regs.
	 *
	 * @return the fire lic num doc of this licns user regs
	 */
	@AutoEscape
	public String getFireLicNumDoc();

	/**
	 * Sets the fire lic num doc of this licns user regs.
	 *
	 * @param fireLicNumDoc the fire lic num doc of this licns user regs
	 */
	public void setFireLicNumDoc(String fireLicNumDoc);

	/**
	 * Returns the product type of this licns user regs.
	 *
	 * @return the product type of this licns user regs
	 */
	@AutoEscape
	public String getProductType();

	/**
	 * Sets the product type of this licns user regs.
	 *
	 * @param productType the product type of this licns user regs
	 */
	public void setProductType(String productType);

	@Override
	public licnsUserRegs cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}