/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.dealer.registration.service.base;

import bd.gov.dgfood.dealer.registration.model.DgfDlrWithdrawal;
import bd.gov.dgfood.dealer.registration.service.DgfDlrWithdrawalLocalService;
import bd.gov.dgfood.dealer.registration.service.DgfDlrWithdrawalLocalServiceUtil;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrPerfDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegAddlDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrUpdtTempDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalFinder;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the dgf dlr withdrawal local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.dealer.registration.service.impl.DgfDlrWithdrawalLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.dealer.registration.service.impl.DgfDlrWithdrawalLocalServiceImpl
 * @generated
 */
public abstract class DgfDlrWithdrawalLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DgfDlrWithdrawalLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DgfDlrWithdrawalLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DgfDlrWithdrawalLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dgf dlr withdrawal to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrWithdrawalLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrWithdrawal the dgf dlr withdrawal
	 * @return the dgf dlr withdrawal that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DgfDlrWithdrawal addDgfDlrWithdrawal(
		DgfDlrWithdrawal dgfDlrWithdrawal) {

		dgfDlrWithdrawal.setNew(true);

		return dgfDlrWithdrawalPersistence.update(dgfDlrWithdrawal);
	}

	/**
	 * Creates a new dgf dlr withdrawal with the primary key. Does not add the dgf dlr withdrawal to the database.
	 *
	 * @param dlrWithdrawalId the primary key for the new dgf dlr withdrawal
	 * @return the new dgf dlr withdrawal
	 */
	@Override
	@Transactional(enabled = false)
	public DgfDlrWithdrawal createDgfDlrWithdrawal(long dlrWithdrawalId) {
		return dgfDlrWithdrawalPersistence.create(dlrWithdrawalId);
	}

	/**
	 * Deletes the dgf dlr withdrawal with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrWithdrawalLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dlrWithdrawalId the primary key of the dgf dlr withdrawal
	 * @return the dgf dlr withdrawal that was removed
	 * @throws PortalException if a dgf dlr withdrawal with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DgfDlrWithdrawal deleteDgfDlrWithdrawal(long dlrWithdrawalId)
		throws PortalException {

		return dgfDlrWithdrawalPersistence.remove(dlrWithdrawalId);
	}

	/**
	 * Deletes the dgf dlr withdrawal from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrWithdrawalLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrWithdrawal the dgf dlr withdrawal
	 * @return the dgf dlr withdrawal that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DgfDlrWithdrawal deleteDgfDlrWithdrawal(
		DgfDlrWithdrawal dgfDlrWithdrawal) {

		return dgfDlrWithdrawalPersistence.remove(dgfDlrWithdrawal);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dgfDlrWithdrawalPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DgfDlrWithdrawal.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dgfDlrWithdrawalPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrWithdrawalModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dgfDlrWithdrawalPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrWithdrawalModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dgfDlrWithdrawalPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dgfDlrWithdrawalPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dgfDlrWithdrawalPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DgfDlrWithdrawal fetchDgfDlrWithdrawal(long dlrWithdrawalId) {
		return dgfDlrWithdrawalPersistence.fetchByPrimaryKey(dlrWithdrawalId);
	}

	/**
	 * Returns the dgf dlr withdrawal with the primary key.
	 *
	 * @param dlrWithdrawalId the primary key of the dgf dlr withdrawal
	 * @return the dgf dlr withdrawal
	 * @throws PortalException if a dgf dlr withdrawal with the primary key could not be found
	 */
	@Override
	public DgfDlrWithdrawal getDgfDlrWithdrawal(long dlrWithdrawalId)
		throws PortalException {

		return dgfDlrWithdrawalPersistence.findByPrimaryKey(dlrWithdrawalId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dgfDlrWithdrawalLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DgfDlrWithdrawal.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dlrWithdrawalId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dgfDlrWithdrawalLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DgfDlrWithdrawal.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dlrWithdrawalId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dgfDlrWithdrawalLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DgfDlrWithdrawal.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dlrWithdrawalId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgfDlrWithdrawalPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement DgfDlrWithdrawalLocalServiceImpl#deleteDgfDlrWithdrawal(DgfDlrWithdrawal) to avoid orphaned data");
		}

		return dgfDlrWithdrawalLocalService.deleteDgfDlrWithdrawal(
			(DgfDlrWithdrawal)persistedModel);
	}

	@Override
	public BasePersistence<DgfDlrWithdrawal> getBasePersistence() {
		return dgfDlrWithdrawalPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgfDlrWithdrawalPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dgf dlr withdrawals.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrWithdrawalModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dgf dlr withdrawals
	 * @param end the upper bound of the range of dgf dlr withdrawals (not inclusive)
	 * @return the range of dgf dlr withdrawals
	 */
	@Override
	public List<DgfDlrWithdrawal> getDgfDlrWithdrawals(int start, int end) {
		return dgfDlrWithdrawalPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dgf dlr withdrawals.
	 *
	 * @return the number of dgf dlr withdrawals
	 */
	@Override
	public int getDgfDlrWithdrawalsCount() {
		return dgfDlrWithdrawalPersistence.countAll();
	}

	/**
	 * Updates the dgf dlr withdrawal in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrWithdrawalLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrWithdrawal the dgf dlr withdrawal
	 * @return the dgf dlr withdrawal that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DgfDlrWithdrawal updateDgfDlrWithdrawal(
		DgfDlrWithdrawal dgfDlrWithdrawal) {

		return dgfDlrWithdrawalPersistence.update(dgfDlrWithdrawal);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DgfDlrWithdrawalLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dgfDlrWithdrawalLocalService = (DgfDlrWithdrawalLocalService)aopProxy;

		_setLocalServiceUtilService(dgfDlrWithdrawalLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DgfDlrWithdrawalLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DgfDlrWithdrawal.class;
	}

	protected String getModelClassName() {
		return DgfDlrWithdrawal.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dgfDlrWithdrawalPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DgfDlrWithdrawalLocalService dgfDlrWithdrawalLocalService) {

		try {
			Field field =
				DgfDlrWithdrawalLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dgfDlrWithdrawalLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DgfDlrPerfDtlsPersistence dgfDlrPerfDtlsPersistence;

	@Reference
	protected DgfDlrRegAddlDtlsPersistence dgfDlrRegAddlDtlsPersistence;

	@Reference
	protected DgfDlrRegDtlsPersistence dgfDlrRegDtlsPersistence;

	@Reference
	protected DgfDlrUpdtTempDtlsPersistence dgfDlrUpdtTempDtlsPersistence;

	protected DgfDlrWithdrawalLocalService dgfDlrWithdrawalLocalService;

	@Reference
	protected DgfDlrWithdrawalPersistence dgfDlrWithdrawalPersistence;

	@Reference
	protected DgfDlrWithdrawalFinder dgfDlrWithdrawalFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		DgfDlrWithdrawalLocalServiceBaseImpl.class);

}