/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.dealer.registration.service.base;

import bd.gov.dgfood.dealer.registration.model.DgfDlrRegDtls;
import bd.gov.dgfood.dealer.registration.service.DgfDlrRegDtlsService;
import bd.gov.dgfood.dealer.registration.service.DgfDlrRegDtlsServiceUtil;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrPerfDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegAddlDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrUpdtTempDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalFinder;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the dgf dlr reg dtls remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.dealer.registration.service.impl.DgfDlrRegDtlsServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.dealer.registration.service.impl.DgfDlrRegDtlsServiceImpl
 * @generated
 */
public abstract class DgfDlrRegDtlsServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, DgfDlrRegDtlsService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DgfDlrRegDtlsService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DgfDlrRegDtlsServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DgfDlrRegDtlsService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dgfDlrRegDtlsService = (DgfDlrRegDtlsService)aopProxy;

		_setServiceUtilService(dgfDlrRegDtlsService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DgfDlrRegDtlsService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DgfDlrRegDtls.class;
	}

	protected String getModelClassName() {
		return DgfDlrRegDtls.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dgfDlrRegDtlsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		DgfDlrRegDtlsService dgfDlrRegDtlsService) {

		try {
			Field field = DgfDlrRegDtlsServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, dgfDlrRegDtlsService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DgfDlrPerfDtlsPersistence dgfDlrPerfDtlsPersistence;

	@Reference
	protected DgfDlrRegAddlDtlsPersistence dgfDlrRegAddlDtlsPersistence;

	@Reference
	protected
		bd.gov.dgfood.dealer.registration.service.DgfDlrRegDtlsLocalService
			dgfDlrRegDtlsLocalService;

	protected DgfDlrRegDtlsService dgfDlrRegDtlsService;

	@Reference
	protected DgfDlrRegDtlsPersistence dgfDlrRegDtlsPersistence;

	@Reference
	protected DgfDlrUpdtTempDtlsPersistence dgfDlrUpdtTempDtlsPersistence;

	@Reference
	protected DgfDlrWithdrawalPersistence dgfDlrWithdrawalPersistence;

	@Reference
	protected DgfDlrWithdrawalFinder dgfDlrWithdrawalFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		DgfDlrRegDtlsServiceBaseImpl.class);

}