/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.dealer.registration.service.base;

import bd.gov.dgfood.dealer.registration.model.DgfDlrUpdtTempDtls;
import bd.gov.dgfood.dealer.registration.service.DgfDlrUpdtTempDtlsLocalService;
import bd.gov.dgfood.dealer.registration.service.DgfDlrUpdtTempDtlsLocalServiceUtil;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrPerfDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegAddlDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrRegDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrUpdtTempDtlsPersistence;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalFinder;
import bd.gov.dgfood.dealer.registration.service.persistence.DgfDlrWithdrawalPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the dgf dlr updt temp dtls local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.dealer.registration.service.impl.DgfDlrUpdtTempDtlsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.dealer.registration.service.impl.DgfDlrUpdtTempDtlsLocalServiceImpl
 * @generated
 */
public abstract class DgfDlrUpdtTempDtlsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DgfDlrUpdtTempDtlsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DgfDlrUpdtTempDtlsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DgfDlrUpdtTempDtlsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dgf dlr updt temp dtls to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrUpdtTempDtlsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrUpdtTempDtls the dgf dlr updt temp dtls
	 * @return the dgf dlr updt temp dtls that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DgfDlrUpdtTempDtls addDgfDlrUpdtTempDtls(
		DgfDlrUpdtTempDtls dgfDlrUpdtTempDtls) {

		dgfDlrUpdtTempDtls.setNew(true);

		return dgfDlrUpdtTempDtlsPersistence.update(dgfDlrUpdtTempDtls);
	}

	/**
	 * Creates a new dgf dlr updt temp dtls with the primary key. Does not add the dgf dlr updt temp dtls to the database.
	 *
	 * @param dgfDlrUpdateReqId the primary key for the new dgf dlr updt temp dtls
	 * @return the new dgf dlr updt temp dtls
	 */
	@Override
	@Transactional(enabled = false)
	public DgfDlrUpdtTempDtls createDgfDlrUpdtTempDtls(long dgfDlrUpdateReqId) {
		return dgfDlrUpdtTempDtlsPersistence.create(dgfDlrUpdateReqId);
	}

	/**
	 * Deletes the dgf dlr updt temp dtls with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrUpdtTempDtlsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrUpdateReqId the primary key of the dgf dlr updt temp dtls
	 * @return the dgf dlr updt temp dtls that was removed
	 * @throws PortalException if a dgf dlr updt temp dtls with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DgfDlrUpdtTempDtls deleteDgfDlrUpdtTempDtls(long dgfDlrUpdateReqId)
		throws PortalException {

		return dgfDlrUpdtTempDtlsPersistence.remove(dgfDlrUpdateReqId);
	}

	/**
	 * Deletes the dgf dlr updt temp dtls from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrUpdtTempDtlsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrUpdtTempDtls the dgf dlr updt temp dtls
	 * @return the dgf dlr updt temp dtls that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DgfDlrUpdtTempDtls deleteDgfDlrUpdtTempDtls(
		DgfDlrUpdtTempDtls dgfDlrUpdtTempDtls) {

		return dgfDlrUpdtTempDtlsPersistence.remove(dgfDlrUpdtTempDtls);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dgfDlrUpdtTempDtlsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DgfDlrUpdtTempDtls.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dgfDlrUpdtTempDtlsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrUpdtTempDtlsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dgfDlrUpdtTempDtlsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrUpdtTempDtlsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dgfDlrUpdtTempDtlsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dgfDlrUpdtTempDtlsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dgfDlrUpdtTempDtlsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DgfDlrUpdtTempDtls fetchDgfDlrUpdtTempDtls(long dgfDlrUpdateReqId) {
		return dgfDlrUpdtTempDtlsPersistence.fetchByPrimaryKey(
			dgfDlrUpdateReqId);
	}

	/**
	 * Returns the dgf dlr updt temp dtls with the primary key.
	 *
	 * @param dgfDlrUpdateReqId the primary key of the dgf dlr updt temp dtls
	 * @return the dgf dlr updt temp dtls
	 * @throws PortalException if a dgf dlr updt temp dtls with the primary key could not be found
	 */
	@Override
	public DgfDlrUpdtTempDtls getDgfDlrUpdtTempDtls(long dgfDlrUpdateReqId)
		throws PortalException {

		return dgfDlrUpdtTempDtlsPersistence.findByPrimaryKey(
			dgfDlrUpdateReqId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dgfDlrUpdtTempDtlsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DgfDlrUpdtTempDtls.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dgfDlrUpdateReqId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dgfDlrUpdtTempDtlsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DgfDlrUpdtTempDtls.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dgfDlrUpdateReqId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dgfDlrUpdtTempDtlsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DgfDlrUpdtTempDtls.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dgfDlrUpdateReqId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgfDlrUpdtTempDtlsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement DgfDlrUpdtTempDtlsLocalServiceImpl#deleteDgfDlrUpdtTempDtls(DgfDlrUpdtTempDtls) to avoid orphaned data");
		}

		return dgfDlrUpdtTempDtlsLocalService.deleteDgfDlrUpdtTempDtls(
			(DgfDlrUpdtTempDtls)persistedModel);
	}

	@Override
	public BasePersistence<DgfDlrUpdtTempDtls> getBasePersistence() {
		return dgfDlrUpdtTempDtlsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgfDlrUpdtTempDtlsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dgf dlr updt temp dtlses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.dealer.registration.model.impl.DgfDlrUpdtTempDtlsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dgf dlr updt temp dtlses
	 * @param end the upper bound of the range of dgf dlr updt temp dtlses (not inclusive)
	 * @return the range of dgf dlr updt temp dtlses
	 */
	@Override
	public List<DgfDlrUpdtTempDtls> getDgfDlrUpdtTempDtlses(
		int start, int end) {

		return dgfDlrUpdtTempDtlsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dgf dlr updt temp dtlses.
	 *
	 * @return the number of dgf dlr updt temp dtlses
	 */
	@Override
	public int getDgfDlrUpdtTempDtlsesCount() {
		return dgfDlrUpdtTempDtlsPersistence.countAll();
	}

	/**
	 * Updates the dgf dlr updt temp dtls in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DgfDlrUpdtTempDtlsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgfDlrUpdtTempDtls the dgf dlr updt temp dtls
	 * @return the dgf dlr updt temp dtls that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DgfDlrUpdtTempDtls updateDgfDlrUpdtTempDtls(
		DgfDlrUpdtTempDtls dgfDlrUpdtTempDtls) {

		return dgfDlrUpdtTempDtlsPersistence.update(dgfDlrUpdtTempDtls);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DgfDlrUpdtTempDtlsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dgfDlrUpdtTempDtlsLocalService =
			(DgfDlrUpdtTempDtlsLocalService)aopProxy;

		_setLocalServiceUtilService(dgfDlrUpdtTempDtlsLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DgfDlrUpdtTempDtlsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DgfDlrUpdtTempDtls.class;
	}

	protected String getModelClassName() {
		return DgfDlrUpdtTempDtls.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dgfDlrUpdtTempDtlsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DgfDlrUpdtTempDtlsLocalService dgfDlrUpdtTempDtlsLocalService) {

		try {
			Field field =
				DgfDlrUpdtTempDtlsLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dgfDlrUpdtTempDtlsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DgfDlrPerfDtlsPersistence dgfDlrPerfDtlsPersistence;

	@Reference
	protected DgfDlrRegAddlDtlsPersistence dgfDlrRegAddlDtlsPersistence;

	@Reference
	protected DgfDlrRegDtlsPersistence dgfDlrRegDtlsPersistence;

	protected DgfDlrUpdtTempDtlsLocalService dgfDlrUpdtTempDtlsLocalService;

	@Reference
	protected DgfDlrUpdtTempDtlsPersistence dgfDlrUpdtTempDtlsPersistence;

	@Reference
	protected DgfDlrWithdrawalPersistence dgfDlrWithdrawalPersistence;

	@Reference
	protected DgfDlrWithdrawalFinder dgfDlrWithdrawalFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		DgfDlrUpdtTempDtlsLocalServiceBaseImpl.class);

}